### PR TITLE
Test Auto Assign & Welcome

### PR DESCRIPTION
**Pull request by onevnine**
Test again...

### CODE REVIEW

**Comment by onevnine** [comment]
All done 👏

**Comment by ivan-nginx** [comment]
Oh, bot can't assign Organization Team.

**Comment by onevnine** [comment]
fuck trump again

**Comment by ivan-nginx** [comment]
`sentimentBotToxicityThreshold: .6` → need more fuck trump, ahahaha lol fuckside bot i called u

**Comment by ivan-nginx** [comment]
Or maybe he don't work in PR's.

**Comment by Raincal** [comment]
Maybe we should use code owners.
https://github.blog/2017-07-06-introducing-code-owners/

**Comment by 1v9** [comment]
@Raincal It's cool but need creat `CODEOWNERS`, wo have so much files 👏

**Comment by ivan-nginx** [comment]
> Maybe we should use code owners.
> https://github.blog/2017-07-06-introducing-code-owners/
> 
> >  The GitHub Blog**[Introducing code owners - The GitHub Blog](https://github.blog/2017-07-06-introducing-code-owners/)**While effective code review is essential to every successful project, it’s not always clear who should review files—even with GitHub’s reviewer suggestions. Now repository maintainers can define exactly which people and teams need to review

About what u talking, @Raincal ?

**Pull request closed without merging**
