### PR TITLE
Fix several bugs reported in v7.3

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
It's for PJAX and cache. Because menu items on every page is same, the only difference is the active one. So move the script to the front-end would be better.

**Comment by ivan-nginx** [comment]
PJAX don't work with backend?

**Comment by stevenjoezhang** [comment]
It could work, but that means pjax have to refresh the whole menu, just to change a single active menu item... and the animation (velocity & motion) have to play again... it's too complicated
That's why I decided to use front-end script to highlight the active one

**Comment by stevenjoezhang** [comment]
屏幕快照 2019-08-05 上午11 48 18

I did not change the style of RSS or Chat during the reconstruction of the font size. Now Chat looks normal but RSS lacks margin. It's weird...

**Pull request merged**
