### PR TITLE
New Gitalk option: accessToken

### PR DESCRIPTION
**Pull request by hsiangfeng**
## PR Checklist 

- [X] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [X] Tests for the changes was maked (for bug fixes / features).
   - [X] Muse | Mist have been tested.
   - [X] Pisces | Gemini have been tested.
- [X] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [X] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Gitalk update https://github.com/gitalk/gitalk/pull/344

Issue resolved: N/A

## What is the new behavior?

solve use Gitalk apper 「[GitHub API] Deprecation notice for authentication via URL query parameters」

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
gitalk:
  enable: true
  ...
  accessToken: # here
  ...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [X] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Need to wait for the official response from gitalk. I am a bit worried that this repository is not maintained anymore

截屏2020-02-05上午9 24 25

**Comment by hsiangfeng** [comment]
> Need to wait for the official response from gitalk. I am a bit worried that this repository is not maintained anymore
> 
> 截屏2020-02-05上午9 24 25

me too.
so ... maybe give up gitalk, but gitalk very easy to use QAQ

**Comment by stevenjoezhang** [comment]
There are only a few popular comment systems based on github issues:
https://github.com/imsun/gitment
https://github.com/gitalk/gitalk
https://github.com/utterance/utterances

Gitment stopped maintenance two years ago, but can be easily migrated to gitalk. Now we need to study the possibility of using utterances instead: https://github.com/theme-next/hexo-next-utteranc

**Comment by asdf2014** [comment]
@hsiangfeng @stevenjoezhang Can we make the `access_token` parameter optional? That is, add a judgment in `gitalk.swig` to see if the `access_token` parameter has a value.

**Comment by stevenjoezhang** [comment]
@asdf2014 `access_token` parameter was removed hours ago in Gitalk release 1.5.2. In fact, Gitalk has made too many changes recently and we need some time to make the right decision. https://github.com/theme-next/hexo-theme-next/pull/1369

**Comment by asdf2014** [comment]
@stevenjoezhang Thanks a lot.

**Comment by hsiangfeng** [comment]
I think we will wait for Gitalk to stabilize before updating ...
Updated again in one night（ OMG

**Pull request merged**
