### PR TITLE
Fix svg confict in algolia vender

### PR DESCRIPTION
**Pull request by sli1989**
In [former file](https://github.com/theme-next/hexo-theme-next/pull/119/files#diff-a8164b1286413219a3653b987a7ebcba), all svg-related element in blog would be blocked leading to the conflict between algolia and svgs.  [Related issue](https://github.com/theme-next/hexo-theme-next/issues/172).

```diff
+svg path {
+ display: none;
+}
```

In this PR, more exact element are found and blocked using algolia CDN , in this way, other svg-related element can be display usually. More related issues about the missing of SVG can be solved.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Tested on all schemes?

**Comment by sli1989** [comment]
I find a strange phenomenon. With the above commit using CDN, 

1. click on the search box, works fine. but the box can be closed only with clicking the close button instead of clicking outside of the area of the search box. 
2. the 2nd click on the search box, there is a overflow where the search box can't be displayed.


qq 20180315151506

**Comment by ivan-nginx** [comment]
Try to disable sidebar, bug still exists?
On all schemes this bug can be reproduced?

**Comment by sli1989** [comment]
All scheme with local lib or vender CDN, the bug is still exist. Need further investment.

**Comment by ivan-nginx** [comment]
@sli1989 reproduce steps, please. I'll join this pull as remote and trying to test.

**Comment by sli1989** [comment]
1. latest release
1. `algolia_search: enable: true`
1. add [commit](https://github.com/theme-next/hexo-theme-next/pull/173/files).
1. using `git clone https://github.com/theme-next/theme-next-algolia-instant-search source/lib/algolia-instant-search` in `cd themes/next` or  set vendor CDN

```
vendors:
  algolia_instant_js: https://cdn.jsdelivr.net/npm/instantsearch.js@2.4.1/dist/instantsearch.js
  algolia_instant_css: https://cdn.jsdelivr.net/npm/instantsearch.js@2.4.1/dist/instantsearch.min.css
```

5. hexo clean && hexo g && hexo s

**Comment by ivan-nginx** [comment]
U test on your domen or u have any subdomen(s) for tests? If yes, can i see live demo with this? (i'm just not use Algolia and need to register this under new test domen|subdomain; `algolia-search.js?v=6.0.6:11 Algolia Settings are invalid.`)

**Comment by sli1989** [comment]
I haven't push them to the blog, I would do it if i failed to find the bug. I am trying to test on V604.

**Comment by ivan-nginx** [comment]
@sli1989 can u create subdomain for tests, something like `test.http://saili.science`?

**Comment by sli1989** [comment]
Deployed for now in http://saili.science/

**Comment by ivan-nginx** [comment]
So, `local_search` is turned off for now? Where i can see full NexT config?

**Comment by sli1989** [comment]
Just leave the `local_search` alone, i haven't uninstall the `hexo-generator-searchdb`. The full files can be found in [gitlab](https://gitlab.com/sli1989/sli1989.gitlab.io).

**Comment by ivan-nginx** [comment]
I see this config for now as default:

```yml
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true
```

But if u want to use Algolia search, i think need to disable local search:

```
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: false
```
Try it.

**Comment by sli1989** [comment]
emm. i haven't update the repo. I did all like [this](https://github.com/theme-next/hexo-theme-next/pull/173#issuecomment-373290949).

**Comment by ivan-nginx** [comment]
So, u talking about what it's clean repo, right? But in your source code (view-source:http://saili.science/) i see source of `local_search` option (search by `.local-search-pop-overlay`) and Algolia search too (search by `algolia-search.js`). So, i think what both Local and Algolia searches was enabled during this deploy.

**Comment by sli1989** [comment]
Yes, you are right. Solved, just closed only with clicking the close button instead of clicking outside of the area of the search box.

**Comment by ivan-nginx** [comment]
So, bug was in both Algolia and Local searches enabled? I think need to add console warning or something like this on this situation.

**Comment by sli1989** [comment]
I have no svg-related plugin to run test. Just perform same as before to avoid display redundant element when using  CDN vendor. Need screenshots?

**Comment by ivan-nginx** [comment]
No need screenshots. Just explain what's not work for now?

**Comment by sli1989** [comment]
ADDED IN PR CONTENT.

**Comment by ivan-nginx** [comment]
«Squash and merge».

**Pull request merged**
