### PR TITLE
Use nunjucks-compatible syntax & operator

### PR DESCRIPTION
**Pull request by stevenjoezhang**
Swig-template supports `|| && or and`
nunjucks only supports `or and`

https://github.com/mozilla/nunjucks/issues/622

### CODE REVIEW

**Comment by 1v9** [comment]
Maybe need a new label for code style change.

**Comment by ivan-nginx** [comment]
Let's up this set on v8.x? I think no need on v7.

**Comment by ivan-nginx** [comment]
https://github.com/popomore/nunjucks-vs-swig

**Comment by stevenjoezhang** [comment]
See also: https://github.com/hexojs/hexo/pull/2903

**Comment by ivan-nginx** [comment]
Need to rename *.swig on *njk also, I think.

**Comment by stevenjoezhang** [comment]
Yes, we could do this after Hexo drops swig support. The syntax of these two template engines is similar, except for some minor differences:
`json_encode` -> `dump`

**Comment by stevenjoezhang** [comment]
@ivan-nginx @1v9 I tried to use `hexo-renderer-njucks`, but got a strange error:
```
ERROR Template render error: (/Users/StevenJoeZhang/blog/themes/next/layout/tag.njk) [Line 46, Column 4]
  unknown block tag: endfor
Template render error: (/Users/StevenJoeZhang/blog/themes/next/layout/tag.njk) [Line 46, Column 4]
  unknown block tag: endfor
    at Object._prettifyError (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:19:11)
    at Template.getExported (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:605:16)
    at eval (eval at _compile (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:18:5)
    at createTemplate (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:327:11)
    at /Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:339:9
    at next (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/lib.js:286:3)
    at Environment.getTemplate (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:321:9)
    at eval (eval at _compile (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:16:5)
    at createTemplate (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:327:11)
    at /Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:339:9
    at next (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/lib.js:286:3)
    at Environment.getTemplate (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:9:5)
    at Template.render (/Users/StevenJoeZhang/blog/node_modules/nunjucks/src/environment.js:556:10)
    at /Users/StevenJoeZhang/blog/node_modules/hexo-renderer-njucks/index.js:22:27
    at Theme._View.View._compiled (/Users/StevenJoeZhang/blog/node_modules/hexo/lib/theme/view.js:123:48)
    at Theme._View.View.View.render (/Users/StevenJoeZhang/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/StevenJoeZhang/blog/node_modules/hexo/lib/hexo/index.js:349:21
    at tryCatcher (/Users/StevenJoeZhang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/StevenJoeZhang/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/StevenJoeZhang/blog/node_modules/hexo/lib/hexo/router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:474:10)
```

I have no idea why `endfor` tag is not parsed correctly. Migrate to `nunjucks` is not easy as changing the suffix name...

So, this PR works fine, but another PR is needed to handle the `nunjucks` syntax

**Comment by 1v9** [comment]
Hexo hasn't toally switched to nunjucks, but tag plugin used nunjucks to render.

**Comment by stevenjoezhang** [comment]
Yes, so you have to install the plugin first: hexo-renderer-njucks

**Comment by 1v9** [comment]
These nunjucks plugins maintenance is not stable enough, so just wait hexojs/hexo#2903 finished and merged and more...

**Comment by ivan-nginx** [comment]
> hexo-renderer-njucks

There are 3 or maybe more nunjucks plugins, not all in public Hexo directory.

**Comment by stevenjoezhang** [comment]
In fact none is in public Hexo directory. They are all 3rd-party plugin. And I choose the only one that still maintained...

**Comment by ivan-nginx** [comment]
BTW, mb we can create own nunjucks plugin and make him internal in scripts dir?

**Comment by ivan-nginx** [comment]
> And I choose the only one that still maintained...

Which plugin u choose?

**Comment by stevenjoezhang** [comment]
This one: https://github.com/AlynxZhou/hexo-renderer-nunjucks
In its README:
> Both hexo-renderer-nunjucks and hexo-renderer-njk and hexo-renderer-njks are using Nunjucks version 2, and seems their author won't update them to Nunjucks 3. They take the best name in npm, but leave code unmaintained! So I write my own hexo renderer to render my theme ARIA.

**Comment by stevenjoezhang** [comment]
> mb we can create own nunjucks plugin
yes, we can just put it in the `scripts` dir

**Comment by ivan-nginx** [comment]
> > mb we can create own nunjucks plugin
> > yes, we can just put it in the `scripts` dir

So, we must find all possible plugins and create from them the best one.

**Comment by ivan-nginx** [comment]
Also, we can no rename swig extension; we can just add swig to nunjucks renderer, that's all.

**Comment by stevenjoezhang** [comment]
We can't migrate to njk unless we clearly understands the problem
https://github.com/theme-next/hexo-theme-next/pull/1068#issuecomment-518756742

**Pull request merged**
