### PR TITLE
add a minimalist comment -- minivaline

### PR DESCRIPTION
**Pull request by MHuiG**
## PR Checklist 

- [x] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build & CI related changes.
- [ ] Documentation.
- [ ] Translation. 
- [ ] Other... Please describe:

## What is the current behavior?

add a minimalist comment -- minivaline
## What is the new behavior?

[demo site](https://mhuig.github.io/guestbook/)
### How to use?
In NexT `_config.yml`:
```yml
minivaline:
  enable: false
  appid:  # Your leancloud application appid
  appkey:  # Your leancloud application appkey
  placeholder: Write a Comment O(∩_∩)O~~ # Comment box placeholder
  maxNest: 3 # Nest size
  pageSize: 6 # Pagination size
  adminEmailMd5: # The MD5 of Admin Email to show Admin Flag.
  math: true # Support MathJax.
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language:
```

### CODE REVIEW

**Comment by sli1989** [comment]
Docs for NexT is needed in https://theme-next.org/docs/ if possible.

**Comment by stevenjoezhang** [comment]
@MHuiG Thanks for your contribution! This comment system can give new users more choices.
However, the current `_config.yml` file is more than 1000 lines, which makes it difficult for users to find options they need. Would you like to make this feature a plugin and submit it here? https://github.com/theme-next/awesome-next#comment

**Comment by MHuiG** [comment]
> @MHuiG Thanks for your contribution! This comment system can give new users more choices.
> However, the current `_config.yml` file is more than 1000 lines, which makes it difficult for users to find options they need. Would you like to make this feature a plugin and submit it here? https://github.com/theme-next/awesome-next#comment
> 
> >  GitHub**[theme-next/awesome-next](https://github.com/theme-next/awesome-next)**😎 Theme NexT, AWESOME NexT! Contribute to theme-next/awesome-next development by creating an account on GitHub.

Thanks for your suggestion, but I think I don't have much free time to do it.

**Comment by MHuiG** [comment]
> Docs for NexT is needed in https://theme-next.org/docs/ if possible.
> 
> >  NexT**[Documentation](https://theme-next.org/docs/index.html)**NexT User Docs

 Docs in NexT website have been added / updated (for features).
[PR](https://github.com/theme-next/theme-next.org/pull/89)

**Comment by MHuiG** [comment]
The MiniValine-based Next plugin may or may not be completed in the future, so stay tuned.

**Pull request closed without merging**
