### PR TITLE
beautufy the reward button

### PR DESCRIPTION
**Pull request by hybcloud**
## PR Checklist 

- [x] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build & CI related changes.
- [ ] Documentation.
- [ ] Translation. 
- [ ] Other... Please describe: 

## What is the current behavior?

图片
图片
图片
图片

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A

图片
图片
图片
图片
- Link to demo site with this changes: N/A

### How to use?
same as before

### CODE REVIEW

**Comment by jiangtj** [comment]
image
The font color is too close to the background color.

**Comment by hybcloud** [comment]
I belive the choice of color is proper. It might look cheap with dark background if I lighten the :hover reward button font color more

> 
> 
> image
> The font color is too close to the background color.

I belive the choice of color is proper. It might look cheap with dark background if I lighten the :hover reward button font color more

**Comment by aixiu** [comment]
真是越改越难看。以前的还好看一些，
image越来越rh看不清。。

**Comment by hybcloud** [comment]
> 
> 
> 真是越改越难看。以前的还好看一些，
> image越来越看不清。。

当你鼠标放上去的时候才会这样显示

**Comment by aixiu** [comment]
算了，我还是自定义成原来的，圆角的，现在的真欣赏不来，谢谢你。

**Comment by hybcloud** [comment]
啊。。。那真有点对不住。。看起来我好心办坏事了。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiangZi"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 晚上6:49
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com&gt;; 
抄送: "hybcloud"<3048130170@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [theme-next/hexo-theme-next] beautufy the reward button (#1471)





 
算了，我还是自定义成原来的，圆角的，现在的真欣赏不来，谢谢你。

**Comment by aixiu** [comment]
没事，估计是以前的看习惯了，一下子改不过来，我还是先自定义成以前的吧，或许其它人会喜欢。再次感谢你的工作。

**Comment by aixiu** [comment]
给个建议，设置成:
```css
&:hover {
      background: lighten($red, 20%);
      background: #fc6423;
      border: 1px solid transparent;
      color: #fff
```
设置成白色或许有所改变。鼠标指向时字会更清晰

**Pull request merged**
