### PR TITLE
Fix disqus lazyload not working in Safari

### PR DESCRIPTION
**Pull request by daya0576**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
`document.documentElement.scrollTop` always return 0 in safari, so Disqus will never pop up. 
image

## What is the new behavior?
- Safari behaves as correct as Chrome.
- fetching `scrollTop` in realtime to avoid some error, e.g. images lazy-loading or manually resizing browser window.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

---

p.s. PR from a back-end developer, not so familiar with front-end code. Feel free to give me some comments XD. Cheers.

### CODE REVIEW

**Comment by daya0576** [comment]
@tsanie  
cc. @ivan-nginx @sli1989

**Comment by ivan-nginx** [comment]
Can u please show live demo with this bugfix?

**Comment by daya0576** [comment]
> Can u please show live demo with this bugfix?

Sure, check this video for detail. 
https://youtu.be/njDn5PPtb04

**Comment by ivan-nginx** [comment]
And other schemes like Gemini have same behaviour?

**Comment by daya0576** [comment]
> And other schemes like Gemini have same behaviour?

Yes, the root reason: `document.documentElement.scrollTop` always return 0 in **safari**, so Disqus will never pop up.

**Comment by ivan-nginx** [comment]
Thanks! :+1:

**Pull request merged**
