### PR TITLE
Add copyright to clipboard when user copy

### PR DESCRIPTION
**Pull request by Angboo**
## PR Checklist 

- [ ] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml

```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [ ] No.

### CODE REVIEW

**Comment by Angboo** [comment]
@stevenjoezhang I think this should be turned on when "creative_commons" is in use, so it should not be a plugins

**Comment by stevenjoezhang** [comment]
Thank you for your suggestions, but this does affect the reading experience. In fact, the use of creative commons is good enough now, it's a moral issue, not a technical one. As a Hexo theme, we must consider both bloggers and readers. Maybe there will be a better solution in the future.

**Comment by Angboo** [comment]
@stevenjoezhang Sorry, I ignore that, And I will create a plugin for next-theme

**Comment by stevenjoezhang** [comment]
Looking forward to your pull request 🎉

https://github.com/theme-next/awesome-next

**Pull request closed without merging**
