### PR TITLE
add math.cdn to head.swig

### PR DESCRIPTION
**Pull request by yzca**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

head.swig has not generation of math's CDN

Issue Number(s): N/A

## What is the new behavior?

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by sli1989** [comment]
what's the difference after the bugfix. More detailed descriptions would be better.

**Comment by yzca** [comment]
The original head.swig is not included math.mathjax.cdn and math.katex.cdn.
Therefore, the browser did not load the CSS file, showing two times.

**Comment by sli1989** [comment]
which math plugin do you used? My [DEMO site](https://test.saili.science/posts/math-test/) hasn't shown this problem.

You mean [this situation](https://www.zhihu.com/question/267011398)?

**Comment by ivan-nginx** [comment]
@sli1989 mathjax confirmed and already worked with custom renderers ([Math guide](https://github.com/theme-next/hexo-theme-next/blob/master/docs/MATH.md)).
About KateX → I don't test it and can't confirm it.

**Comment by sli1989** [comment]
I use pandoc+mathjax. I will try Katex later.

**Comment by ivan-nginx** [comment]
Official site (still in developing) use Kramed + MathJax.

**Pull request closed without merging**
