### PR TITLE
Make `symbols_count_time` faster

### PR DESCRIPTION
**Pull request by stevenjoezhang**
**Related to https://github.com/theme-next/hexo-symbols-count-time/pull/23**

## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [x] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@stevenjoezhang here is must exists tag BC because with this changes plugin must be update to the latest version.

**Comment by Maples7** [comment]
It seems this PR breaks words count even though after I update `hexo-symbols-count-time` to `0.6.0`?
image

I update theme code to the newest of master (up to this commit: https://github.com/theme-next/hexo-theme-next/commit/7c24d106b05326607269053a81359ade715dd60b) with my own configurations exactly like here: https://github.com/Maples7/blog. By the way, I use `theme_config` field in site config file to do settings.

**Comment by ivan-nginx** [comment]
Question to @stevenjoezhang.

**Comment by ivan-nginx** [comment]
@Maples7, question is solved?

**Comment by Maples7** [comment]
I think so! With `hexo-symbols-count-time@6.0.0` and newest master code up to https://github.com/theme-next/hexo-theme-next/commit/ec648f469f54830169b8ad45a4e43e0b64068317.

**Comment by Maples7** [comment]
Thank you guys very much!

**Pull request merged**
