### PR TITLE
Extract leancloud-counter to plugins (An example of #663)

### PR DESCRIPTION
**Pull request by LEAFERx**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [X] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [X] Tests for the changes was maked (for bug fixes / features).
   - [X] Muse | Mist have been tested.
   - [X] Pisces | Gemini have been tested.
- (**NOT YET**)Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [X] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

leancloud-counter's swig is embedded in NexT

## What is the new behavior?

leancloud-counter is fully extracted as independent plugin.

An example of #663 

### How to use?
In NexT `_config.yml`:
```yml
leancloud_visitors:
  enable: true
```
Further config is and should be done in plugin config.

The plugin is https://github.com/theme-next/hexo-leancloud-counter/

For now, this Pull Request is not hush to be merged since this plugin is just a prototype. I will complete it soo. But actually this plugin can work for now. Also, document will be add soon.

**This PR shows my idea about how to make NexT more simple and pluggable.**

## Does this PR introduce a breaking change?
- [x] Yes.
- [ ] No.

### CODE REVIEW

**Comment by sli1989** [comment]
No information about the configuration of leancloud_counter?
`api_id: config.leancloud_counter.app_id`

**Comment by stevenjoezhang** [comment]
How about uploading it to npmjs.org? Like https://www.npmjs.com/package/hexo-leancloud-counter-security

**Comment by LEAFERx** [comment]
> No information about the configuration of leancloud_counter?
> `api_id: config.leancloud_counter.app_id`

The config is done in plugin config (that is root _config.yml not theme _config.yml).
Like I said, I am working on perfecting this plugin and the document. But I am busy in weekdays(qaq) so it may take some time.


> How about uploading it to npmjs.org? Like https://www.npmjs.com/package/hexo-leancloud-counter-security

checkout https://www.npmjs.com/package/hexo-leancloud-counter

**Comment by ivan-nginx** [comment]
So, as I right understand, no need to add in theme:

- Settings
- Swig templates (if exists)
- CSS templates (if exists)

Only in plugin (Hexo's config) all settings will be? Right?

**Comment by LEAFERx** [comment]
> So, as I right understand, no need to add in theme:
> 
> * Settings
> * Swig templates (if exists)
> * CSS templates (if exists)
> 
> Only in plugin (Hexo's config) all settings will be? Right?

Yes, themes only need to integrate them and manage them (which to show, etc.)

**Comment by LEAFERx** [comment]
Sorry for the misoperation. Continue to #707 .

**Pull request merged**
