### PR TITLE
Bug Fix: Missing a closing bracket

### PR DESCRIPTION
**Pull request by xwhfcenter**
bug: Missing a closing bracket

## PR Checklist 

- [x] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml

```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Do you see the bracket at the end of the line? 😂

截屏2020-02-05下午7 50 23

**Comment by xwhfcenter** [comment]
> Do you see the bracket at the end of the line? 😂
> 
> 截屏2020-02-05下午7 50 23

Oh, I used the stable version and its code is following:
<a href="{{ url_for(theme.menu.archives).split('||')[0] | trim }}">
and it can not work well. 

This branch is OK.

**Comment by stevenjoezhang** [comment]
Both links you provided point to the wrong address
截屏2020-02-06下午12 36 26

I studied the change history of this file and am pretty sure that since the creation of this repository, there has never been a mismatch in brackets.

截屏2020-02-06下午12 27 08

This is not difficult to understand, because bracket is an important operator for javascript. If the bracket problem does exist, we will already receive tons of bug reports, but this is not the case.

**Comment by stevenjoezhang** [comment]
Both links you provided point to the wrong address
截屏2020-02-06下午12 36 26

I studied the change history of this file and am pretty sure that since the creation of this repository, there has never been a mismatch in brackets.

截屏2020-02-06下午12 27 08

This is not difficult to understand, because bracket is an important operator for javascript. If the bracket problem does exist, we will already receive tons of bug reports, but this is not the case.

**Pull request closed without merging**
