### PR TITLE
Added «Thanks» section

### PR DESCRIPTION
**Pull request by ivan-nginx**
Go to this link for see: https://github.com/theme-next/hexo-theme-next/tree/thanks-section

P.S. Need to add translate in `zh-CN`.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@all-contributors please add @stevenjoezhang for review

**Comment by ivan-nginx** [comment]
@all-contributors please add @1v9  for translation

**Comment by ivan-nginx** [comment]
@all-contributors please add @stevenjoezhang for translation.

**Comment by ivan-nginx** [comment]
@all-contributors add @1v9 for review.

**Comment by ivan-nginx** [comment]
@all-contributors add @JiangTJ for infra.

**Comment by sli1989** [comment]
OMG, amazing...

**Comment by ivan-nginx** [comment]
@allcontributors[bot] add @ivan-nginx for design, infra, maintenance.
@allcontributors[bot] add @liolok for projectManagement.

**Comment by ivan-nginx** [comment]
@allcontributorsadd add @ivan-nginx for design, infra, maintenance.

**Comment by ivan-nginx** [comment]
@allcontributors add @liolok for projectManagement.

**Comment by ivan-nginx** [comment]
@allcontributors remove @liolok for code, bug, review, test.

**Comment by ivan-nginx** [comment]
@allcontributorsadd add @ivan-nginx for design, infra, maintenance.

**Comment by stevenjoezhang** [comment]
@all-contributors please add @Maples7 for code, bug

**Comment by stevenjoezhang** [comment]
@all-contributors please add @hsiangfeng  for code, bug

**Comment by stevenjoezhang** [comment]
@all-contributors please add @xyyuchn for doc

**Pull request merged**
