### PR TITLE
Modify some of the descriptions in _config.yml to make them more uniform

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [x] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

There are 40 `enable:` and 4 `enabled:` in `_config.yml`. This PR make them look better.
Issue resolved N/A

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@stevenjoezhang please, describe all changed options with diff style in accordance with this PR.
As u can see, GitHub banner don't show on NexT site for after this changes.

**Comment by stevenjoezhang** [comment]
@ivan-nginx I have wrote the description in `Breaking Change` part... use `enable` instead of `enabled`

**Comment by ivan-nginx** [comment]
> please, describe all changed options

I don't wrote about GitHub, also.

Need to describe something like in #711 PR.

**Comment by stevenjoezhang** [comment]
Could be added to v7.1 release note, I think

**Comment by ivan-nginx** [comment]
> Could be added to v7.1 release note, I think

A repeat: all BC, provided by PR's, must be documented directly in PR's for releases notes. @liolok make releases and he don't understand all code and changes what we doing here.

**Comment by stevenjoezhang** [comment]
Don't worry, I'll write a bot to do so. It's easy for a bot to check out which option was renamed/changed in `_config.yml`.

**Comment by ivan-nginx** [comment]
I'm don't worry, but will worry users. They, like me, will don't see what changes was made. As a result in current case, I didn't even notice about GitHub banner disappearing. So, I had to look where are changes was.

In accordance with that, all this breaking changes must be documented as soon as possible, directly in this PR for now. Are u understand what master branch – is production branch? Peoples updated repo, but lost their changes in settings.

Bot – it's good, but right now need to add diffs changes here. Please, take your time for that. It's more important than answering in issues, for example. Thank's.

**Comment by stevenjoezhang** [comment]
OK. And maybe we can add a note on theme-next.org index page, to alert users about the changes

**Comment by ivan-nginx** [comment]
Joking... I'm just trying to explain u how need to do for best coding in future.
If u forget to add changes now, u may forgot to add changes in future. It's don't take long time, just make a try to used it always.

P.S. Actually, BC one of the bad things which requires some arounding by automation.

**Pull request merged**
