### PR TITLE
Fix duplicate meta tag keywords

### PR DESCRIPTION
**Pull request by Raincal**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

### In post page

Issue Number(s): N/A

## What is the new behavior?
Description about this pull, in several words...
https://github.com/hexojs/hexo/pull/2535
Since this PR, hexo has already generate meta tag "keywords" for us, so we don't need to do that again
* Screens with this changes: N/A
* Link to demo site with this changes: https://raincal.com/
### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@Raincal can u provide some *md post example with this changes?

**Comment by Raincal** [comment]
2018-02-09 01 50 47 am

Add some keywords or tags in post. You can see this bug.

**Comment by ivan-nginx** [comment]
So, if there are no will `keywords`, but `tags` only?

**Comment by Raincal** [comment]
2018-02-09 01 56 11 am
http://sh.alynx.xyz/
https://rainylog.com/
These sites have this problem now. You can see it online.

**Comment by wafer-li** [comment]
Confirmed.

image

Only contain `tags` without `keywords`, and there is the duplication.

**Comment by ivan-nginx** [comment]
I see what for now bug exists with duplicate, but i'm not totally sure what fix is not missing something.
Can u please test it guys to all possible cases? OpenGraph, Twitter, Homepage, Sinlepage, Post, Cats, Tags, Tagspage, Catspage, Archives. Duplicate for now not critical for SEo, but if something will lose this will more bugly then bug this duplicate.

***

I just can't to test in production for now.

**Comment by ivan-nginx** [comment]
@xu-song what are u talking about? Give some example, for what it need.

**Comment by ivan-nginx** [comment]
This pull will be released in **NexT v6.0.6** and minimal requirements for [**Hexo version 3.3.5**](https://github.com/hexojs/hexo/releases/tag/3.3.5).

**Comment by xu-song** [comment]
Both `Hexo` and `theme-next` will insert `<meta name="keywords"`  to html.
If `Hexo` has insered  `<meta name="keywords"`  to html, `theme-next` do not need to insert another one. @

**Comment by ivan-nginx** [comment]
So, for now NexT not insert `<meta name="keywords"` with Hexo v3.5.5 and highter.
Or u want to use older Hexo version?

**Comment by xu-song** [comment]
In my opinion, all the following code should be deleted. 

```js
{% if page.keywords %}
  <meta name="keywords" content="{{ page.keywords }}" />
{% elif page.tags and page.tags.length %}
  <meta name="keywords" content="{% for tag in page.tags %}{{ tag.name }},{% endfor %}" />
{% elif theme.keywords %}
  <meta name="keywords" content="{{ theme.keywords }}" />
{% endif %}
```
`keywords` can be defined in `Hexo config.yml`.

**Comment by ivan-nginx** [comment]
This pull already merged. If u want to do some improvement to this, u can create new pull request. Thank's!

**Pull request merged**
