### PR TITLE
Increase generation speed with `cache` option.

### PR DESCRIPTION
**Pull request by ivan-nginx**
Resume of #545 pull.

***

Guys, need to test all 3rd-party libs to be sure it's worked.
**Before all test not passed, this PR can't be merged.**

- [x] Sidebar (need to recheck on all schemes)
- [ ] TOC (breaked with `hexo g`)
- [ ] Disqus (breaked with `hexo g`)

***

- [ ] `vendors.swig`
- [ ] `commons.swig`
- [ ] `scheme_script`
- [ ] `boostrap.swig`
- [ ] `_third-party/comments/index.swig`
- [ ] `_third-party/search/index.swig`
- [ ] `_third-party/analytics/lean-analytics.swig`
- [ ] `_third-party/analytics/firestore.swig`
- [ ] `_third-party/seo/baidu-push.swig`
- [ ] `_third-party/schedule.swig`
- [ ] `_third-party/math/index.swig`
- [ ] `_third-party/needsharebutton.swig`
- [ ] `_third-party/rating.swig`
- [ ] `_third-party/pangu.swig`
- [ ] `_third-party/scroll-cookie.swig`
- [ ] `_third-party/exturl.swig`
- [ ] `_third-party/bookmark.swig`
- [ ] `_third-party/copy-code.swig`
- [ ] `_third-party/pdf.swig`

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@JiangTJ 
> TOC isn't fixed yet.
> I tested disqus. Disqus is also mistake for every posts.

About TOC & Disqus... it's strange, but when i tested it on localhost with `hexo s` – they work fine. I think only with `hexo g` this error appear. Can you confirm it?

**Comment by JiangTJ** [comment]
I got this issue in both hexo s and hexo s.
Maybe issue in submenu, cached toc and disqus are in submenu.
[this page toc and disqus](
https://jiangtj.gitlab.io/next-test/gemini/docs) be cached

**Comment by ivan-nginx** [comment]
> `hexo s` and `hexo s`?

**Comment by JiangTJ** [comment]
:joy: sorry, both hexo s and hexo g
homepage error may be same with toc

**Comment by ivan-nginx** [comment]
So, i can't catch this error with `hexo clean && hexo s`:

Homepage:
image

Post:
image

Docs:
image

Another docs:
image

**Comment by JiangTJ** [comment]
Emmm...  seems only `hexo g`, but why there are different?
image
image
image
image

**Comment by ivan-nginx** [comment]
* Can you provide your NexT `_config`?
* You use any additional cache via Gitlab?
* Can you try to reproduce same error with `[NexT site config & posts & plugins](https://github.com/theme-next/theme-next.org)`, and generate it to empty `gh-pages` (or Gitlab).
* If cache will turned off, this error still exists?

**Comment by stevenjoezhang** [comment]
Seems `hexo s` only generates the page you requested, so the cache isn't actually working?

**Comment by JiangTJ** [comment]
all in here https://gitlab.com/JiangTJ/next-test
theme and some docs file download in ci

**Comment by ivan-nginx** [comment]
> Seems `hexo s` only generates the page you requested, so the cache isn't actually working?

Maybe.

**Comment by stevenjoezhang** [comment]
I reproduced the same issue, TOC breaked with `hexo g`.
The component which is the same in every page, works fine.

**Comment by cocobear** [comment]
this PR not merged into v6.7 , but it's closed, why?

**Comment by ivan-nginx** [comment]
It's have a bugs with wrong cached links. Wait a while, bugfix will be added in both v6 & v7 versions.

**Pull request closed without merging**
