### PR TITLE
fix: busuanzi counter display bug

### PR DESCRIPTION
**Pull request by nature1995**
Do not show count in homepage when access it at the first time.

## PR Checklist 

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

The busuanzi counter can display properly.

Issue resolved: Yes

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml

```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Would you like to have a discussion with @Liam0205 ?
https://github.com/theme-next/hexo-theme-next/pull/1154
https://github.com/theme-next/hexo-theme-next/pull/1154/files

**Comment by nature1995** [comment]
因为之前写的没check通过，我就从新pull了一下

**Comment by stevenjoezhang** [comment]
那也不需要重新开一个，你只用force push到自己的分支即可。

**Comment by nature1995** [comment]
不好意思，下次注意

**Comment by Liam0205** [comment]
As mentioned in the original issue post, setting `display: none` helps busuanzi hide itself when busuanzi asynchronous scripts are not executed, which prevents broken result.

This is not a bug, but a feature.

**Comment by nature1995** [comment]
> As mentioned in the original issue post, setting `display: none` helps busuanzi hide itself when busuanzi asynchronous scripts are not executed, which prevents broken result.
> 
> This is not a bug, but a feature.

I think it need to display at the first time to access,  or you could add an option which can have a choice for the user.

**Comment by Liam0205** [comment]
> > As mentioned in the original issue post, setting `display: none` helps busuanzi hide itself when busuanzi asynchronous scripts are not executed, which prevents broken result.
> > This is not a bug, but a feature.
> 
> I think it need to display at the first time to access, or you could add an option which can have a choice for the user.

I'm not quite understand.

As you could found in the documentation of `busuanzi`, setting `display: none` is a recommended practice. This prevents broken display when asynchronous scripts are not executed, and when these scripts are well executed, the `display` property of the container will be correctly set again, which results in correct display.

Again: this is not a bug, this is a feature.

**Comment by nature1995** [comment]
> > > As mentioned in the original issue post, setting `display: none` helps busuanzi hide itself when busuanzi asynchronous scripts are not executed, which prevents broken result.
> > > This is not a bug, but a feature.
> > 
> > 
> > I think it need to display at the first time to access, or you could add an option which can have a choice for the user.
> 
> I'm not quite understand.
> 
> As you could found in the documentation of `busuanzi`, setting `display: none` is a recommended practice. This prevents broken display when asynchronous scripts are not executed, and when these scripts are well executed, the `display` property of the container will be correctly set again, which results in correct display.
> 
> Again: this is not a bug, this is a feature.

I just see the doc in busuanzi's site which show below.
4、在访问量数据未取回来之前，我不想让页面显示为诸如“本站总访问量 次”，显得太low，怎么办？
只需要如下css，不蒜子执行完毕会自动将标签显示出来，其他以此类推：
```
<span id="busuanzi_container_site_pv" style='display:none'>
    本站总访问量<span id="busuanzi_value_site_pv"></span>次
</span>
```

**Comment by Liam0205** [comment]
> > > > As mentioned in the original issue post, setting `display: none` helps busuanzi hide itself when busuanzi asynchronous scripts are not executed, which prevents broken result.
> > > > This is not a bug, but a feature.
> > > 
> > > 
> > > I think it need to display at the first time to access, or you could add an option which can have a choice for the user.
> > 
> > 
> > I'm not quite understand.
> > As you could found in the documentation of `busuanzi`, setting `display: none` is a recommended practice. This prevents broken display when asynchronous scripts are not executed, and when these scripts are well executed, the `display` property of the container will be correctly set again, which results in correct display.
> > Again: this is not a bug, this is a feature.
> 
> I just see the doc in busuanzi's site which show below.
> 4、在访问量数据未取回来之前，我不想让页面显示为诸如“本站总访问量 次”，显得太low，怎么办？
> 只需要如下css，不蒜子执行完毕会自动将标签显示出来，其他以此类推：
> 
> ```
> <span id="busuanzi_container_site_pv" style='display:none'>
>     本站总访问量<span id="busuanzi_value_site_pv"></span>次
> </span>
> ```

doesn't this sustain my point of view?

**Comment by nature1995** [comment]
> > > > > As mentioned in the original issue post, setting `display: none` helps busuanzi hide itself when busuanzi asynchronous scripts are not executed, which prevents broken result.
> > > > > This is not a bug, but a feature.
> > > > 
> > > > 
> > > > I think it need to display at the first time to access, or you could add an option which can have a choice for the user.
> > > 
> > > 
> > > I'm not quite understand.
> > > As you could found in the documentation of `busuanzi`, setting `display: none` is a recommended practice. This prevents broken display when asynchronous scripts are not executed, and when these scripts are well executed, the `display` property of the container will be correctly set again, which results in correct display.
> > > Again: this is not a bug, this is a feature.
> > 
> > 
> > I just see the doc in busuanzi's site which show below.
> > 4、在访问量数据未取回来之前，我不想让页面显示为诸如“本站总访问量 次”，显得太low，怎么办？
> > 只需要如下css，不蒜子执行完毕会自动将标签显示出来，其他以此类推：
> > ```
> > <span id="busuanzi_container_site_pv" style='display:none'>
> >     本站总访问量<span id="busuanzi_value_site_pv"></span>次
> > </span>
> > ```
> 
> doesn't this sustain my point of view?

But it can't display after loading in the first time.

**Comment by Liam0205** [comment]
Nonsense! After execution, the `display` property of the container will be modified to `display: inline` automatically.

Things works fine on my blog and on my test site. If you insist, provide a complete path for reproducing the problem.

**Comment by nature1995** [comment]
It still not display in the first time. It is diplayed after refresh the site.

image

**Comment by Liam0205** [comment]
> It still not display in the first time. It is diplayed after refresh the site.
> 
> image

As requested before, provide a complete path for reproducing the problem.

**Comment by mystic-cg** [comment]
I found that if you both enabled **live2d** and **busuanzi**, which causes that busuanzi **style="display: none"**.
If you disabled live2d, busuanzi would work well.

**Comment by nature1995** [comment]
> I found that if you both enabled **live2d** and **busuanzi**, which causes that busuanzi **style="display: none"**.
> If you disabled live2d, busuanzi would work well.

I think you are right. It the same situation as me.

**Comment by stevenjoezhang** [comment]
If you guys can solve the problem after disabling live2d, then it sounds like it's not a bug of busuanzi.

**Comment by Liam0205** [comment]
That's why I asked for a complete path for reproducing the problem, since we have no idea about what you had done before you enabled busuanzi.

**Comment by stevenjoezhang** [comment]
> I found that if you both enabled live2d and busuanzi, which causes that busuanzi style="display: none".
If you disabled live2d, busuanzi would work well.

I'm not sure which plugin you are using, but this has proven that this is not a bug in the theme NexT. Please ask the maintainer of the plugin for help.
I also have a live2d plugin that is compatible with busuanzi. If you are interested, you can check it out: https://github.com/stevenjoezhang/live2d-widget

**Comment by stevenjoezhang** [comment]
正常情况下， busuanzi 会向 head 中 append 的一个 script 标签名为 scriptTag，用于加载数据；数据加载完成后，通过 `scriptTag.parentElement.removeChild(scriptTag)` 移除之；在启用 hexo-helper-live2d 时，`scriptTag.parentElement` 为 null （原因未知），导致 try catch 语句执行，通过 `bszTag.hides()` 将页面上的所有统计数据隐藏。我个人没有兴趣浪费更多时间研究此问题，因此建议不要同时使用 busuanzi 和 hexo-helper-live2d。考虑到此问题与 NexT 主题本身无关，请联系这两个项目的维护者讨论和解决。

**Comment by ouuan** [comment]
关于 busuanzi 和 live2d 共同使用的问题，我找到了根本原因，写了篇博客: https://ouuan.moe/post/2022/08/busuanzi-and-live2d

**Pull request closed without merging**
