### PR TITLE
New Valine options

### PR DESCRIPTION
**Pull request by kuretru**
## PR Checklist 

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [x] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
valine:
   recordIP: true # Whether to record the commenter IP
   serverURLs: https://api.your_domian.com # When the custom domain name is enabled, fill it in here (itwill be detected automatically by default, no need to fill in)
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by 1v9** [comment]
Seems fine, any demo?

**Comment by kuretru** [comment]
> Seems fine, any demo?

Sure, there is my config in _config.yml:
```
valine:
  recordIP: true
  serverURLs: https://api.blog.i5zhen.com
```
For serverURLs:
1. Open my blog: [https://blog.kuretru.com/posts/bb1d45aa.html](https://blog.kuretru.com/posts/bb1d45aa.html) . 
2. Open the Console -> Network tab in Chrome, you can see some XHR request like "/Comment?where=xxxxxxx"
3. The request host is "https://api.blog.i5zhen.com/1.1/classes/Comment?where=xxxxxxx", which is set in my config.

For recordIP:
* In my LeanCloud console, The commenter's IP is recorded correctly.
* You can find Valine request a XHR in Chrome, like: "https://api.ip.sb/jsonip?callback=getIP", used to get commenter's IP.

**Comment by 1v9** [comment]
@all-contributors please add @kuretru for code, doc

**Comment by kuretru** [comment]
Thanks for @1v9 .

**Comment by 1v9** [comment]
@kuleyu 可以来 TG 群里吹逼

**Comment by pzb568** [comment]
Valine没有绑定域名，是不是就不能使用了呢

**Comment by kuretru** [comment]
> Valine没有绑定域名，是不是就不能使用了呢

根据[官方文档](https://valine.js.org/configuration.html#serverURLs)，这个选项不设置的话，会自动检测并配置。  
提示：旧版本的Valine确实存在bug，可以手动指定Valine版本至1.3.10+

**Pull request merged**
