### PR TITLE
Fix Group Pictures layout

### PR DESCRIPTION
**Pull request by 1v9**
Related issues: #713 #929.
Current layouts of GP in page and post are different and wrong.

### CODE REVIEW

**Comment by 1v9** [comment]
Found some other layout broken in different schemes, it's a disaster...

**Comment by 1v9** [comment]
As I wrote above, I only modified minor styles, but the layouts in different schemes, including **page** and **post**, have a lot of weird CSS problems that are beyond my ability. This does not even involve the potential js part we talked before. 😅

Insert `layout: post` into the front-matter of the page containing the group pictures through some hexo filter?

**Comment by khoint0210** [comment]
This work like a charm merges it plzzz... 😢

**Comment by stevenjoezhang** [comment]
https://github.com/iissnan/hexo-theme-next/issues/295#issuecomment-127322681

其实iissnan的原始设计就是这样，grouppicture只在index page有效，在点进去之后就是每行一张图片的样式
当然这个PR也没有问题，只是grouppicture必须配合fancybox或者medium zoom才能达到效果

**Pull request merged**
