### PR TITLE
Comment counter

### LINKED ISSUE #271: Optimize the loading of comment counter
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

on my blog ,comment limit loading rate of sit, that maybe also for many users.
although some comment plug-in not block the main thread on page showing, it still load and a loading icon show on chrome status bar. others plug-in even block the page showing.
i used gitment,youyan,changyan,LiveRe , now i used valine,
1. comment counter default loading on homepage.
i think there should be a option to control the comment counter plug-in in homepage also postpage.
if i set show 5 post in homepage , there will be 10 http requests, and cdn won't work on it;
screenshot from 2018-05-04 12-24-57

2. some js file url should write in _config.yml such as
https://github.com/theme-next/hexo-theme-next/blob/d4475e5d99f3fe04ed450e52600d3ab1ae0425bb/layout/_third-party/comments/valine.swig#L1-L3
https://github.com/theme-next/hexo-theme-next/blob/d4475e5d99f3fe04ed450e52600d3ab1ae0425bb/layout/_third-party/analytics/lean-analytics.swig#L3-L5
cdn1.lncld.net is really slow

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): #271

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
As this is Feature, need to merge in into v7 branch. Wait, i will create version branches, need to manage something with it.

**Comment by ivan-nginx** [comment]
Why you do this?) Literals will be used in NexT v7 (soon). Take a roll back, we will use literals by default in this year, it's good and conveniently.

Don't be so quickly. I said before: «Wait, i will create version branches, need to manage something with it».

**Comment by stevenjoezhang** [comment]
This PR solved problem 1 in https://github.com/theme-next/hexo-theme-next/issues/271
And literals could be added to https://github.com/theme-next/hexo-theme-next/pull/557
Things are getting complicated ... I think 😂

**Comment by ivan-nginx** [comment]
> And literals could be added to #557

Ok, add it in #557 PR.
Also, try to separate feaures / bugfixes / optimizations in future. Just create separated local branch and you can move commits from any branch here. With Cherry-pick, for example. Also, try to use GitKraken.

**Comment by stevenjoezhang** [comment]
@ivan-nginx Thanks for your advice, I have to admit I'm not so good at using git.
Besides, The current `layout/_third-party/analytics/lean-analytics.swig`(https://github.com/theme-next/hexo-theme-next/blob/master/layout/_third-party/analytics/lean-analytics.swig) is already using literals, and it was added in https://github.com/theme-next/hexo-theme-next/commit/3a921ce5d794550fc81c493f80886a6342ffaebf#diff-d4f96cf2cea92b9d7c8d95bb034e2eb2, but we haven't receive any error reports in the past several months. So, is it really important to keep supporting IE? (https://caniuse.com/#search=Template%20Literals) Maintaining two mainline versions would be challenging.

**Comment by ivan-nginx** [comment]
IE will support only old v6.x, that's why need to separate versions.
Template literals need to use in new v7.x. It's at least bring global refactoring in engine, so, major version must be changed.

> Maintaining two mainline versions would be challenging

For now i'm write issue about it and as i see, it's didn't hard to maintenance. But need to make choice: what we will include and what not.

For now do what you do, create pulls into master (it's will be v7) and don't worry about it.

**Pull request merged**
