### PR TITLE
fix if not is post show the commit

### PR DESCRIPTION
**Pull request by Mryan2005**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [ ] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
What's the difference? `{%- if page.comments %}` is enough to make comments only display on page and post

**Comment by Mryan2005** [comment]
but you can't stop show it in Tag page and categoriespage

**Comment by Mryan2005** [comment]
@stevenjoezhang

**Comment by stevenjoezhang** [comment]
You can take a look at the discussion in this PR: https://github.com/theme-next/hexo-theme-next/pull/1039

Comments can be disabled by setting `comments` to `false` in Front-matter. In other words, users have the right to choose whether the comments display in tags or archive page.
However, this PR fully disabled the comments in tags or archive page. Users can't enable comments without modifying source code.

**Comment by Mryan2005** [comment]
ok. I see

**Pull request closed without merging**
