### PR TITLE
Update the post modify text for unification

### PR DESCRIPTION
**Pull request by sli1989**
Before

qq 20180414190919

After

qq 20180414191724

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@sli1989 hi and please, wait with this pull before #228 pull not ready.

**Comment by sli1989** [comment]
I think they are unrelated. Just modify the display text.
And is it necessary to change the translation of `post.created` and `post.modified` into `Post created time` and `Post modified time`.

https://github.com/theme-next/hexo-theme-next/blob/05d43f81e6b3c811e97e0862055e4be107049cb7/languages/en.yml#L25-L26

**Comment by ivan-nginx** [comment]
`Post created:` $date
`Post modified:` $date

?

**Comment by sli1989** [comment]
no no... they are pop-up annotation for the diapalyed`Posted on $date`. I mean the fixed text `created: Post created time`.

**Comment by ivan-nginx** [comment]
I understand. Need some time, please, wait.

**Comment by ivan-nginx** [comment]
Already added in #228 pull. Thank's!

**Pull request closed without merging**
