### PR TITLE
Contributors per line: 6 instead of 7

### PR DESCRIPTION
**Pull request by ivan-nginx**

### CODE REVIEW

**Comment by 1v9** [comment]
I have a question that I always want to ask! 😂

**Comment by stevenjoezhang** [comment]
Need to regenerate README? It's still 7 per line

**Comment by ivan-nginx** [comment]
Yeah, it seems bot have some bugs. For example, if 2 contributors was added (2 pulls created) in second pull merge will conflict.

Moreover, maybe better will use not `README.md` file, but any another file? (can be defined in bot's config).

**Comment by stevenjoezhang** [comment]
Like this one: https://github.com/theme-next/hexo-theme-next/blob/master/docs/AUTHORS.md ?

**Comment by ivan-nginx** [comment]
Maybe yes. I think must be named «MAINTAINERS.md» or «CONTRIBUTORS.md».

**Comment by stevenjoezhang** [comment]
And maybe we can add more 3rd party applications to this part:

屏幕快照 2019-03-30 上午12 58 30

**Comment by ivan-nginx** [comment]
See Telegram chat.

**Comment by ivan-nginx** [comment]
I'll [assigned to it](https://github.com/theme-next/hexo-theme-next/projects/3) in #758.

**Pull request merged**
