### PR TITLE
Use Object.assign instead of lodash merge

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [x] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
See: https://www.measurethat.net/Benchmarks/Show/2978/0/lodash-merge-vs-objectassign-vs-spread

**Comment by jiangtj** [comment]
How about to support deep copy?

**Comment by stevenjoezhang** [comment]
Like what...

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/blob/5067852e5f5ba4883064716b530c664ec0feeafc/.gitattributes

**Comment by jiangtj** [comment]
image
image
image

😂

**Comment by jiangtj** [comment]
Hexo support `lodash`
image

**Comment by jiangtj** [comment]
> Hexo support `lodash`

But I don't how to use 😂 
image

**Comment by stevenjoezhang** [comment]
I see. So it would better be
obj = Object.assign(obj, other)

**Comment by jiangtj** [comment]
> I see. So it would better be
> obj = Object.assign(obj, other)

I don't know, I also use `Object.assign` 😂 . But `_.merge` and `Object.assign` behave differently, need to pay attention or remind the user.

**Comment by 1v9** [comment]
@jiangtj `const merge = require('lodash/merge');`

**Comment by 1v9** [comment]
So, `lodash merge` vs `Object.assign` vs `Spread syntax`? Shadow copy? Deep copy? 😂

**Comment by stevenjoezhang** [comment]
Problems occur if a user does not copy all sub-options under a root option...
In this particular case, `Object.assign` and `lodash.merge` have different properties
Since this is a function that executes only once, the performance issue is less critical to consider
So revert it: https://github.com/theme-next/hexo-theme-next/commit/74f27495b993f338633c985a11e243ea7499a1e4

**Comment by stevenjoezhang** [comment]
Revert啦，忽略呀

**Pull request merged**
