### PR TITLE
Multilingual switch button support

### LINKED ISSUE #1070: Multilingual support
Add a multilingual button for switching the website into different language version(contents of different language must be separated).

### PR DESCRIPTION
**Pull request by stevenjoezhang**
Issue resolved: #1070

```diff
+# Show multilingual switcher in footer.
+language_switcher: false
```

### CODE REVIEW

**Comment by ZhaoEli** [comment]
大神，可以开发一个文章底部点赞功能么！

**Comment by stevenjoezhang** [comment]
已经有了，直接用就行。

**Comment by stevenjoezhang** [comment]
Currently `hexo-generator-index` does not generate separate homepages for posts in different languages. For example,
```
source/
    _posts/
        zh-cn/
            post-zh.md
        en/
            post-en.md
```
Both posts will appear in the index page (`/index.html` , but not one in `/index.html` and the other in `/zh-cn/index.html`) - Unless you write your own script, modify configuration (e.g. `url` and `root` in `_config.yml`) and source files, then execute `hexo g` multiple times; or use 3rd-party plugins like `hexo-generator-i18n`.

Therefore, this pull requestis only partially done. Full multi-language support needs to wait for the hexo generator implementation.

**Comment by suyin-long** [comment]
这个效果怎么看不错来呢？设置后那个切换语言的按钮在哪呢？

**Comment by rexwangcc** [comment]
@suyin-long 需要在next/_config.yml中设置 `language_switcher: true`, 之后会在footer（页面的最下端）显示一个小图标。不满意位置的话可以自行定义sidebar等模板来放置这个选择框。

**Comment by zhengfc** [comment]
图标是显示在底部了，一点击的话就是404了；模板要能根据选择语言读语言配置文件的数据就好了；这样至少整体页面结构首先就能切换了

**Comment by dirname** [comment]
> @suyin-long 需要在next/_config.yml中设置 `language_switcher: true`, 之后会在footer（页面的最下端）显示一个小图标。不满意位置的话可以自行定义sidebar等模板来放置这个选择框。

你好，我设置了 `language_switcher: true` 以后，好像没有图标在 _footer_ 显示，是需要其他额外的设置吗

**Comment by Gabirel** [comment]
> Currently `hexo-generator-index` does not generate separate homepages for posts in different languages. For example,
> 
> ```
> source/
>     _posts/
>         zh-cn/
>             post-zh.md
>         en/
>             post-en.md
> ```
> 
> Both posts will appear in the index page (`/index.html` , but not one in `/index.html` and the other in `/zh-cn/index.html`) - Unless you write your own script, modify configuration (e.g. `url` and `root` in `_config.yml`) and source files, then execute `hexo g` multiple times; or use 3rd-party plugins like `hexo-generator-i18n`.
> 
> Therefore, this pull requestis only partially done. Full multi-language support needs to wait for the hexo generator implementation.


I've made it generate automatically and works very well.
Note for setting up multilingual website：
1. Combine [hexojs/hexo-generator-index](https://github.com/hexojs/hexo-generator-index) and [xcatliu/hexo-generator-index-i18n](https://github.com/xcatliu/hexo-generator-index-i18n)
2. Create your posts via `hexo new --lang ja "This is a new title"`
3. `hexo clean && hexo g && hexo s`

**Comment by doutv** [comment]
> > @suyin-long 需要在next/_config.yml中设置 `language_switcher: true`, 之后会在footer（页面的最下端）显示一个小图标。不满意位置的话可以自行定义sidebar等模板来放置这个选择框。
> 
> 你好，我设置了 `language_switcher: true` 以后，好像没有图标在 _footer_ 显示，是需要其他额外的设置吗


需要在根目录下的 _config.yml 修改 language，只有 `language_switcher: true` 且 language 数量大于 1，才会显示
```yaml
language:
- en
- zh-CN
```

**Comment by Happylinzy** [comment]
修改语言后，侧边栏的tag，categories等按钮需要在source目录下设置对应语言文件夹下的index才能替换。但是点击跳转还是回到默认的英文路径下

**Pull request merged**
