### PR TITLE
add reading_progress

### PR DESCRIPTION
**Pull request by maple3142**
## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
N/A

Issue Number(s): N/A

## What is the new behavior?
A scroll bar on the top in post pages.

* Screens with this changes: [video](https://streamable.com/dymvy)
* Link to demo site with this changes: [https://blog.maple3142.net/](https://blog.maple3142.net/)

### How to use?
In NexT `_config.yml`: 
Find "reading_progress" field and enable it
```yml
reading_progress:
  enable: false
  color: "#37c6c0"
  height: 2px
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

I am not sure where I put css and js is correct.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Hi dude!

1. Can u please test it with `pace` (Progress bar in the top during page loading.)?
2. I think this feature need to move to external repo, like `pace`, `fancybox`, etc. What u think?

**Comment by maple3142** [comment]
It will be override by pace, but work as usual after loaded.
And I moved it to [external repo](https://github.com/theme-next/theme-next-reading-progress), but css and html still remains in main repo.
Because it needs to detect current page is a post or not.

**Comment by ivan-nginx** [comment]
OK, can u add switch on CSS loading?

Something like:
```scss
@import "post-reading_progress" if hexo-config('reading_progress.enable');
```

**Comment by maple3142** [comment]
Yes, it worked fine with pace.

**Comment by ivan-nginx** [comment]
Ok, cool. Thanks and GJ!

**Comment by ivan-nginx** [comment]
@maple3142 hi again, i'm forgot to say to u add in `_config.yml` dependencies link, like in other repos. Can u?

**Pull request merged**
