### PR TITLE
Remove all hardcoded font sizes with replacing them on `em`

### PR DESCRIPTION
**Pull request by ivan-nginx**
Resuming for #723 pull.

### CODE REVIEW

**Comment by 1v9** [comment]
@ivan-nginx @stevenjoezhang I‘ve fixed conflicts, now my [site](https://1v9.im) is basing on `font-refactoring` branch. It's nice, font size is like before. Is there any work need to do?

**Comment by ivan-nginx** [comment]
> Is there any work need to do?

Yes, there is.

**Comment by stevenjoezhang** [comment]
I prefer to merge this PR, because it resolved 3 issues:  #249, #687 and #629.
Using `em` instead of `px` is nice, should open another PR to do so

**Comment by 1v9** [comment]
@stevenjoezhang Agree, in my view this PR has been put on hold for too long.

**Comment by ivan-nginx** [comment]
No need to fast with this PR. I'll try to switch on `em` at once.

**Comment by stevenjoezhang** [comment]
`Removed all hardcoded font sizes` is bugfix (for `code` font-size, and it's high priority)
`with replacing them on em`is feature & improvment (low priority)

As a bug fix, I think it is still necessary to be merged ASAP. Switch on `em` at once is not a good idea - I remember you have always told me to do only one thing in a single PR.

**Comment by 1v9** [comment]
> `Removed all hardcoded font sizes` is bugfix (for `code` font-size, and it's high priority)
> `with replacing them on em`is feature & improvment (low priority)
> 
> As a bug fix, I think it is still necessary to be merged ASAP. Switch on `em` at once is not a good idea - I remember you have always told me to do only one thing in a single PR.

Nice counterattack!😉

**Comment by ivan-nginx** [comment]
> `Removed all hardcoded font sizes` is bugfix (for `code` font-size, and it's high priority)
> `with replacing them on em`is feature & improvment (low priority)
> 
> As a bug fix, I think it is still necessary to be merged ASAP. Switch on `em` at once is not a good idea - I remember you have always told me to do only one thing in a single PR.

I remember it too, yeah. But there is another situation: more things I've seen – breaked. It's actually most global refactoring, and move like this can't be only bugfix. If we start to refactor fonts, to remove hardcore styles, to change font sizes, etc., well, needed to make it beautiful. Making it at once and forgot about it...

As about talking mixed features / bugfixes / improvements: I will not edit in this PR button styles, fixes in swig or additions in js, u know? I'll do only what related to the Fonts, no less no more. And seems this PR not enter in tomorrow release, because there are many, many changes and need to carefully test it too. Important thing: don't hurry. Coz we already have a lot of changes in future v7.1.0 release.

**Comment by ivan-nginx** [comment]
And actually this will be Improvement. Not Bug Fix and not Feature. Just Font will be better = Improvement.

**Comment by stevenjoezhang** [comment]
@ivan-nginx So, is there any progress?

**Comment by ivan-nginx** [comment]
Ok, I'll see it detailed later. For now as I see, seems it what NexT needed. Alse, I don't find headers (H1-H6), I was implemented this function from Gemini (deleted lines in this PR). Don't hurry, we make this fonts to ideal.

**Comment by stevenjoezhang** [comment]
@ivan-nginx 
>  I don't find headers (H1-H6)
They're still here, you can check again
> I was implemented this function from Gemini (deleted lines in this PR)
No need to resume them. Why they were deleted? Because the target of this PR is **Remove all hardcoded font sizes**

You can push your changes/commits to font-refactoring branch, and I'll merge my commits, then let's do the further tests. Don't hurry, but can be more efficiency.

**Comment by stevenjoezhang** [comment]
Besides, is this bot working properly?

屏幕快照 2019-04-02 下午6 50 24

**Comment by ivan-nginx** [comment]
> Besides, is this bot working properly?
> 
> 屏幕快照 2019-04-02 下午6 50 24

WIP bot exists in this PR because he was installed during creation this PR. In new PR's all will be fine.

**Comment by stevenjoezhang** [comment]
Superseded by #1005, #1006

**Pull request closed without merging**
