### PR TITLE
Moved `source/js/src` to `source/js`

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [x] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
You can help check if I forgot to change anything related to `/js/src`. This PR can wait until v7.1.1/v7.2.0 release

**Comment by ivan-nginx** [comment]
1. Are here exists Breaking Change?
2. Are we need to add this to `v6.x`?

**Comment by 1v9** [comment]
I have widened my eyes 😂 and have not found any omissions.

**Comment by 1v9** [comment]
I just added [Work In Progress](https://probot.github.io/apps/wip/), this is a test, you can remove `WIP` to pass the check.

**Comment by 1v9** [comment]
@wip ready for review

**Comment by stevenjoezhang** [comment]
What does `Expected — Waiting for status to be reported` mean?

**Comment by 1v9** [comment]
> What does `Expected — Waiting for status to be reported` mean?

See [here](https://github.com/theme-next/hexo-theme-next/pull/744#issuecomment-478201657), I will update PR template.

**Comment by ivan-nginx** [comment]
It seems all done and this PR can be merged without problems.

**Pull request merged**
