### PR TITLE
Mathjax configuration for linebreaks

### PR DESCRIPTION
**Pull request by stevenjoezhang**
**Feature: If a math equation rendered by mathjax is longer than the screen width, it will be separeted to two lines automatically.
如果一个由Mathjax渲染的公式超出了屏幕宽度（比如在iPhone上查看一个较长的公式），默认行为将导致出现横向滚动条，非常不美观。这个PR解决了此问题，以使公式自动换行。**

### Demo
Create a new blog file, e.g. Mathjax_sample.md, which contains:
```
---
title: Mathjax_sample
categories: Other
date: 2018-10-31 10:48:48
tags:
mathjax: true
---
\begin{align\*}
\pi^{-z}\zeta(2z)\Gamma(z)&=\int_0^{+\infty}\left(\sum_{n=1}^\infty e^{-\pi n^2s}\right)s^{z-1}ds\\\\
&=\int_0^{+\infty}\psi(s)s^{z-1}ds
\end{align\*}
Thus
\begin{align\*}
\pi^{-z}\zeta(2z)\Gamma(z)&=\int_0^{+\infty}\psi(s)s^{z-1}ds\\\\
&=\int_1^{+\infty}\psi(s)s^{z-1}ds+\int_0^1\psi(s)s^{z-1}ds\\\\
&=\int_1^{+\infty}\psi(s)s^{z-1}ds+\int_1^{+\infty}\psi\left(\frac{1}{s}\right)s^{1-z}\frac{ds}{s^2}\\\\
&=\int_1^{+\infty}\psi(s)s^{z-1}ds+\int_1^{+\infty}\left(\psi(s)\sqrt{s}+\frac{\sqrt{s}-1}{2}\right)s^{-1-z}ds\\\\
&=\int_1^{+\infty}\psi(s)(s^{z-1}+s^{-z-\frac{1}{2}})ds+\int_1^{+\infty}\frac{s^{-z-\frac{1}{2}}-s^{-z-1}}{2}ds\\\\
&=\int_1^{+\infty}\psi(s)(s^{z-1}+s^{-z-\frac{1}{2}})ds+\frac{1}{2z(2z-1)}
\end{align\*}
```

### What is the current behavior?
Screenshot on my iPhone:

As you can see, the equation is overflowed.

### CODE REVIEW

**Comment by sli1989** [comment]
demos is recommended to add. 😄

**Comment by sli1989** [comment]
It seems unworkable for me. https://test.saili.science/posts/math-test/
Do you know why. 

image

**Comment by reuixiy** [comment]
@stevenjoezhang Actually, there is a more simpler solution. Just add the following CSS code:

```css
.MathJax_Display {
    overflow: auto hidden;
}
```

workspace 1_001

peek 2018-11-01 10-51

It works well:

1. Simple
2. Much better than `line-break` (Personally)

**Comment by stevenjoezhang** [comment]
I dont't know why either 😢. According to the [documentation](http://docs.mathjax.org/en/latest/output.html)  of Mathjax:
> ## Automatic Line Breaking
>Line breaking only applies to displayed equations, not in-line equations (unless the in-line equation is itself longer than a line), and the line-breaks are only computed once when the equation is initially typeset, and do not change if the user changes the window size, or if the container changes size for some other reason.
>You can control what width is used to determine where the line breaks shoud occur using the container parameter of the linebreaks block. By default it is the width of the containing element, but you can make it a fixed width, or make it a percentage of the container. See the CommonHTML configuration, HTML-CSS configuration, or SVG configuration pages for more details.
>Note that breaks occur only at operations and relations or at explicit space, but not, for example, in the middle of two consecutive identifiers, and long identifiers or numbers are not broken, nor are the contents of <mtext> elements (which come from the \text{} macro in TeX input).
>The line-breaking algorithm uses the nesting depth, the type of operator, the size of spaces, and other factors to decide on the breakpoints, but it does not know the meaning of the mathematics, and may not choose the optimal breakpoints. We continue to work on the algorithm as we gain information from its actual use in the field. If you are using MathML as your input format, you can use the linebreak="newline", linebreak="goodbreak", linebreak="badbreak", and linebreak="nobreak" attributes on <mo> elements to help MathJax pick the best breakpoints for your mathematics; nested <mrow> elements will reduce the risk of breaking its children apart. For TeX input, you can use MathJax’s non-standard mmltoken macro (e.g., \mmlToken{mo}[linebreak="goodbreak"]{}) and braces {...} respectively to achieve analoguous effects.

There seems to be no good solution. You can try this:
```
<style>
.MathJax_Display {
    overflow-x: scroll;
    overflow-y: hidden;
}
</style>
```
It may solve the problem, but not in a native way.

**Comment by ivan-nginx** [comment]
@stevenjoezhang never do rebase. Merge from `dev` to `master` is the best variant.

**Comment by stevenjoezhang** [comment]
@ivan-nginx Got it.

**Comment by sli1989** [comment]
@stevenjoezhang i have fixed it with css style in #488 .
if u have more perfect solution, please not hesitate to take a pr, and make sure all codes are clear and concise.
thanks.

**Pull request closed without merging**
