### PR TITLE
Refactor several components in `_config.yml`

### PR DESCRIPTION
**Pull request by stevenjoezhang**
# Breaking change

Deleted:
`avatar.opacity`
`codeblock.border_radius`

Renamed:
`highlight_theme` -> `codeblock.highlight_theme`
`custom_logo.image` -> `custom_logo`
`pace_theme` -> `pace.theme`

```diff
avatar:
-  opacity: 1

-highlight_theme: normal
codeblock:
+  highlight_theme: normal
-  border_radius:

-custom_logo:
-  enable: false
-  image: #/uploads/custom-logo.jpg
+custom_logo: #/uploads/custom-logo.jpg

-pace: false
-pace_theme: pace-theme-minimal
+pace:
+  enable: false
+  theme: minimal
```

In `_config.yml`, `avatar.opacity` and `codeblock.border_radius` only changes the style of one particular class of elements.
As a result of #868, creating custom css is unprecedented in simplicity. These options should be removed and users can use custom css instead.
Besides, `codeblock.border_radius` should follow `codeblock.copy_button.style`

## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [x] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: #299

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [x] Yes.
- [ ] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Able to merge now?

**Comment by sli1989** [comment]
1. how to set `codeblock.border_radius` according to [copy-code.styl](https://github.com/theme-next/hexo-theme-next/blob/183e5b1bae84f6d07c6071270c1c46da16fd9082/source/css/_common/components/highlight/copy-code.styl)?
1. about `avatar.opacity`, this also should be reset?
https://github.com/theme-next/hexo-theme-next/blob/57289bca5cc70dd37ca3fae00b14309ebfa56a98/source/css/_common/components/sidebar/sidebar-author.styl#L8

**Comment by stevenjoezhang** [comment]
About the second question, it has already been reset. You can check the master branch.

**Comment by sli1989** [comment]
oh, thanks. but how to custom these two css for xiaobai. 😢

**Comment by stevenjoezhang** [comment]
Add this to `_data/styles.styl`:
```css
.site-author-image {
 opacity: 0.7;
}
```

**Comment by ivan-nginx** [comment]
> Add this to `_data/styles.styl`:
> 
> ```css
> .site-author-image {
>  opacity: 0.7;
> }
> ```

Answers like that must be documented in site for around excess questions.

**Comment by 1v9** [comment]
@ivan-nginx FAQ?

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/theme-next.org/issues/36

**Comment by ivan-nginx** [comment]
> @ivan-nginx FAQ?

Yep.

**Pull request merged**
