### PR TITLE
Cache sidebar site-overview

### PR DESCRIPTION
**Pull request by jiangtj**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [x] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
https://github.com/theme-next/hexo-theme-next/pull/545
https://github.com/theme-next/hexo-theme-next/issues/539
https://github.com/theme-next/hexo-theme-next/issues/661

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by jiangtj** [comment]
Add a little cache, this time just the sidebar.... :joy:

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/pull/547

**Comment by jiangtj** [comment]
> #547

Tested in https://jiangtj.gitlab.io/next-test/gemini/, TOC is OK, because I don't cache it.

我知道有许多地方需要缓存，但是一点点来会更好，避免出错。。。
I know there are many places that need to be cached, but it will be better in a little bit to avoid mistakes. . . 
:worried:

**Comment by Liam0205** [comment]
test report:

* base: v7.2.0, compare: #971 .
* generating time costing: 10+min, 1.3min.

GJ! thanks @jiangtj

**Comment by Liam0205** [comment]
BTW, next time, you could notify me on GitHub issue. @jiangtj

**Comment by jiangtj** [comment]
> BTW, next time, you could notify me on GitHub issue. @jiangtj

😂 Okay, thank you for your test.

Others still need to be cached, it is expected to be around 1min. Waiting next time.

**Pull request merged**
