### PR TITLE
Menu external url

### PR DESCRIPTION
**Pull request by jiangtj**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
Menu didn't support jump to external links

Issue Number(s): N/A

## What is the new behavior?
Menu support jump to external links
image
click google  jump to www.google.com

Config in the end of [this file](https://gitlab.com/JiangTJ/next-test/blob/master/_config.yml) 
Previews:
- Muse <https://jiangtj.gitlab.io/next-test/muse>
- Mist <https://jiangtj.gitlab.io/next-test/mist>
- Pisces <https://jiangtj.gitlab.io/next-test/pisces>
- Gemini <https://jiangtj.gitlab.io/next-test/gemini>

### How to use?
In NexT `_config.yml`:
```yml
  menu:
    home: / || home
    archives: /archives/ || archive
    google: https://www.google.com || google
    more:
      default: /more/ || info
      google: http://www.google.com || google
      more:
        google: https://www.google.com || google
        default: /more/ || info
```
**Note**
`default` is not supported, due to `default` is used for displaying some submenu info.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Review by sli1989 — CHANGES_REQUESTED** [review]

**Comment by sli1989** [comment]
well, i understand.
it's better to add explanatory note  about this.

**Comment by JiangTJ** [comment]
:joy: I don't know where to add explanatory note, because there's no note about submenu.

**Comment by ivan-nginx** [comment]
@JiangTJ just add here in this PR something like readme. Later it will be on main site.

**Comment by JiangTJ** [comment]
@ivan-nginx okay，I updated this PR, Add **note** in `How to use`

**Comment by ivan-nginx** [comment]
@JiangTJ maybe #463 PR ([v6.6.0](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.6.0)) already solved this problem. Please, check it.

**Comment by JiangTJ** [comment]
@ivan-nginx this PR didn't solve it.

**Comment by ivan-nginx** [comment]
@JiangTJ can you give some explanation on it, what currently didn't work? Because on your [test site](https://jiangtj.gitlab.io/next-test/gemini/) «Google» links work fine.

**Comment by JiangTJ** [comment]
@ivan-nginx 
In my test site, deploy `two-branch`, it merge `menu-external-url` and `fix-same-submenu`
Current Behavior:
image

**Comment by JiangTJ** [comment]
This json is generated in deploy.  It show deploy repo and branch info 
https://jiangtj.gitlab.io/next-test/deploy.json

**Comment by ivan-nginx** [comment]
Ok, i check and confirm it. But i remember what in #463 PR i tested «Google» (external) links and they working fine.

1. Maybe #496 PR make this bug?
2. On your site you use latest master branch or latest release (v.6.6.0) version?

**Comment by JiangTJ** [comment]
@ivan-nginx 
image
You may only test outermost menu

**Comment by ivan-nginx** [comment]
So, the only problem for **this PR**:

1. Main menu work with «Google» links.
2. Submenu and sub-submenu not work with «Google» links?

**Comment by JiangTJ** [comment]
Emmm...  For main menu, generated link is https:/www.google.com, it lost `/` and it isn't correct link.
But on most browser, work 'fine'...

**Comment by ivan-nginx** [comment]
@JiangTJ thanks for bugfixes for [NexT](https://theme-next.org)!

**Comment by Brannua** [comment]
Hi, may i ask a question ? I'm using the latest version of Next.

My site URL is `xxx.com`, and i want to set `xxx.com/sub` as a external_link.

However, because of the domain is not changed, so the `xxx.com/sub` is not open in a new tab.

If there is way to open `xxx.com/sub` in a new tab when i click it in menu ?

**Comment by Brannua** [comment]
@ivan-nginx Is there any solutions ? thanks very much.

**Pull request merged**
