### PR TITLE
Add valine template , update cdn url

### PR DESCRIPTION
**Pull request by 799953468**
## PR Checklist 

- [x] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build & CI related changes.
- [ ] Documentation.
- [ ] Translation. 
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: #1475

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
valine:
  enableQQ: true # Whether to enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  # See: https://valine.js.org/emoji.html
  emojiCDN: 
  emojiMaps: 
```

### CODE REVIEW

**Comment by sli1989** [comment]
@xCss any reviews? The comments are integrated with inject now.

**Comment by jiangtj** [comment]
@sli1989 from the modified position, there is no problem, but I do not have a valine account. Can you help to test this branch and agree or request changes?

**Comment by xCss** [comment]
@sli1989 @jiangtj  It looks fine, but it needs to be tested locally.

I can't run the program locally for environmental reasons. I need your help to test it. Thx!

**Comment by sli1989** [comment]
https://github.com/next-theme/hexo-theme-next/pull/62

**Pull request closed without merging**
