### PR TITLE
two bugs . The one is the tip of comments-number,the anther is that plugin hexo-all-minifier changs the 'QR' to ' qr' so that the reward button not to ues.

### PR DESCRIPTION
**Pull request by Lruihao**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved N/A

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by liolok** [comment]
Please write pull request in a better style, and I suppose this pr should be written as two different one.

**Comment by Lruihao** [comment]
ok，i will pr again as two different.

**Comment by liolok** [comment]
@Lruihao Thanks for your work. Please write more details and refer to other PRs for style.

**Comment by liolok** [comment]
> ok，i will pr again as two different.

@Lruihao I edited title for this time, could you please add details for others to understand?

**Comment by Lruihao** [comment]
sorry,my english is so poor!haha,and in fact，my commit just fixs two simple bugs that one makes comment count friendly,and   other one fixs the disable reward buttom bug cause of the plugin hexo-all-minifier.

**Comment by liolok** [comment]
@Lruihao I'm just a newbie here to make monthly release. I haven't contributed any code to now, so I'm appreciate for your work. But, it's also necessary to fill the descriptions like both current behavior and new behavior, text and screenshots, to make other people know about what changes this pull request make. If you are not familiar with these stuff, you could go check other PRs, most of them are clear.

**Comment by stevenjoezhang** [comment]
Element id `QR` has been renamed to `qr`. See https://github.com/theme-next/hexo-theme-next/commit/8cc79e5ba775b63499644bcc22662991ef372da2

**Pull request merged**
