### PR TITLE
fix: add dot make gitalk.swig work

### PR DESCRIPTION
**Pull request by umm233**
## PR Checklist 

- [x] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

miss a comma in the gitalk.swig make it work unexpectly.
Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml

```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Thanks for your contributing, however, gitalk released two new versions a day ago, removing this newly added option: https://github.com/theme-next/hexo-theme-next/pull/1369 😂

**Comment by umm233** [comment]
> Thanks for your contributing, however, gitalk released two new versions a day ago, removing this newly added option: #1369 😂

ok, I don't notice it 😂, I will close it.

**Comment by stevenjoezhang** [comment]
If you find other issues with gitalk, please feel free to report to us 😊

**Comment by umm233** [comment]
> If you find other issues with gitalk, please feel free to report to us 😊

ok

**Pull request closed without merging**
