### PR TITLE
Make per_page default to true to make math lazyloaded

### PR DESCRIPTION
**Pull request by wafer-li**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
`per_page` default is `false` and will render math EVERY PAGE.

## What is the new behavior?

`per_page` default is `true` and will render math on demand.

That is it will only render those posts with `mathjax: true` by default

Related: https://github.com/theme-next/hexo-theme-next/pull/32#issuecomment-359286588

### How to use?
In NexT `_config.yml`:
```yml
# This is default opiton now
math:
  enable: false
  per_page: true
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
It's just optiomization.

**Comment by ivan-nginx** [comment]
And milestone please.

**Comment by sli1989** [comment]
好吧，还以为改了代码。为啥不考虑删除not呀，为了保持一致性？

**Comment by baoang** [comment]
正在用这个功能。我觉得单页比较好，因为不是每一篇博客都含有数学化学等公式的，如果每页均要引入mathjax的话，对页面的加载来说是个负担。

目前我的做法就是在含有数学公式的md文件的头部加个`mathjax: true`

**Comment by sli1989** [comment]
The question is the logic: `per_page: true`=not load per page. 😄

**Pull request merged**
