### PR TITLE
Remove full-image tag

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [x] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [x] Yes.
- [ ] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
References:
https://github.com/theme-next/hexo-theme-next/commit/5a70fd32c5565771e93de5c364b4596c5a197e07
https://github.com/theme-next/hexo-theme-next/commit/08eb90e60be132076037aa1b373b7c3f2671de50
https://github.com/theme-next/hexo-theme-next/issues/52
https://github.com/iissnan/hexo-theme-next/issues/1911

**Comment by ivan-nginx** [comment]
1. It's actually no Feature, but BC.
2. How about Lazy loading Image?
3. How about refactoring FI into something about [that](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/DOCUMENTATION.md#wide-image)?

I don't understand why in so little period so many removes & refactoring.

**Comment by stevenjoezhang** [comment]
About Lazy loading Image, just enable `lazyload` in `_config.yml`. See: https://github.com/theme-next/hexo-theme-next/pull/957

There is no sidebar affix in the legacy version of NexT: https://notes.iissnan.com/, so full-image / wide-image is a nice feature. As for now, I recommend that users use mediumzoom to achieve similar results.

**Comment by stevenjoezhang** [comment]
About Lazy loading Image, just enable `lazyload` in `_config.yml`. See: https://github.com/theme-next/hexo-theme-next/pull/957

There is no sidebar affix in the legacy version of NexT: https://notes.iissnan.com/, so full-image / wide-image is a nice feature. As for now, I recommend that users use mediumzoom to achieve similar results.

**Comment by ivan-nginx** [comment]
> About Lazy loading Image, just enable lazyload in _config.yml. See: #957

Yea, but with this option lazyloaded will be all images. With tag it can be single. Or not can be.

**Comment by stevenjoezhang** [comment]
The main problem is that the style in v7.x has changed a lot compared to v5.x
`.post-block` has a padding of 40px which makes it impossible to control the width of full image

**Pull request merged**
