### PR TITLE
Refine Simplified Chinese Translations and Add Translations for documents in Simplified Chinese.

### PR DESCRIPTION
**Pull request by Blealtan**
## PR Checklist

- [ ] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).\
  > What are the guidelines on commit message? I can't access the [documentation site](https://theme-next.org) currently.
- [ ] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [x] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

* `post/totalcount` and `post/totaltime` in `languages/zh-Hans.yml` are not translated.
* Documentations under `docs/cn` are not translated.

Issue Number(s): N/A

## What is the new behavior?

* Untranslated words in `zh-Hans` are now translated.
* Translations for documentations, including `DATA-FILES.md`, `INSTALLATION.md` and `README.md`, are finished.

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?

N/A.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Cool and thank u!
But need to wait a moment: i write additional docs right now, so, can u wait a little and then do full translate of new files?

**Comment by Blealtan** [comment]
Yeah of course. I'll wait for further updates and translate them.

**Comment by ivan-nginx** [comment]
It's ready. This commit: https://github.com/theme-next/hexo-theme-next/commit/3eebd5f9818d1d0105d0ffa9d7dca88fdd056065

**Comment by ivan-nginx** [comment]
Fixed, this commit: https://github.com/theme-next/hexo-theme-next/commit/3fbb71570c23fc98e16173cb37edd2cf9d6b26cc

**Comment by Blealtan** [comment]
`INSTALLATION.md` is updated and translation for `UPDATE-FROM-5.1.x.md` is added. In the translation of the latter one I made some style changes as for Markdown best practices. You may want check it before accepting.

**Comment by ivan-nginx** [comment]
Cool dude! Thank's a lot! :+1:

**Pull request merged**
