### PR TITLE
Delete documents that are no longer needed

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [x] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
@ivan-nginx I guess I have told you in the telegram chat:
https://github.com/theme-next/theme-next-algolia-instant-search/tree/master/docs
https://github.com/theme-next/hexo-leancloud-counter-security/tree/master/docs

**Comment by ivan-nginx** [comment]
1. Must be on website.
2. Must be EN + CN, u delete four files, not 2.

**Comment by stevenjoezhang** [comment]
Website don't have Chinese version now.

**Comment by ivan-nginx** [comment]
> Website don't have Chinese version now.

This no mean need to delete that docs. Just put it under `_post/zh-cn` or `_post/zh-tw` directory. Permalinks must work always.

**Comment by ivan-nginx** [comment]
And first of all, need to sync this docs to the docs on website. Copmpare them, which newer? Maybe split them, etc.

**Comment by ivan-nginx** [comment]
But actually I think, before we have no multi-language support, no need to touch this docs too. I don't know why u move this docs to modules repo...

**Comment by stevenjoezhang** [comment]
If you want to remove `docs/` folder, you have to find a new place for these files

**Comment by ivan-nginx** [comment]
> Website don't have Chinese/Russian version now.

So, hy u move this docs **now**? I talk what this need to do, but not now, not tomorrow or something like that.

**Comment by stevenjoezhang** [comment]
Of course, not now... that's why I open an PR instead of commit directly

**Comment by ivan-nginx** [comment]
> you have to find a new place for these files

Yes. This place will one place – NExT website. What u can't to understand? Why need to move docs in many other places? With which services u will translate it? Are u know what in Crowdin, for example, linit on repos?

**Comment by ivan-nginx** [comment]
> Of course, not now... that's why I open an PR instead of commit directly

So, why to open PR now? Are docs folder excess for u or what?
And whu docs already here: https://github.com/theme-next/hexo-leancloud-counter-security/tree/master/docs
And here: https://github.com/theme-next/theme-next-algolia-instant-search/tree/master/docs

**Comment by stevenjoezhang** [comment]
屏幕快照 2019-04-01 下午5 57 40

Obviously, the types of docs in `docs/` folder is quite different.

**Comment by ivan-nginx** [comment]
@stevenjoezhang can u just forgot in some time about that docs before we don't egin translate NexT site?
And before translate NexT site, need to implement milti-language function, right?
Function not exists in NexT, but u move the docs it is not clear why. From NexT to modules, from modules to site? Why so excess moves?

**Comment by ivan-nginx** [comment]
> 屏幕快照 2019-04-01 下午5 57 40
> 
> Obviously, the types of docs in `docs/` folder is quite different.

Of course i know it, dude. If all will be easy, docs directory already was empty. See above what I told.
Meta will be in `.github` directory, 3rd-party – in website. Relax, dude. No need to move the docs from one to another repo, better do the code... bugs, features, refactoring, etc. I'll make to complete with this docs, may hard things about it in my head, but will be solved.

Just make this link:
# See: https://github.com/theme-next/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md
On NexT sebsite, on Algolia. And another one (LC) maby need to add to website too.

**Comment by stevenjoezhang** [comment]
If one day we will move the docs out in the future, these changes are necessary. You can make it `Working in progress` or something, and do the works you like.

**Comment by ivan-nginx** [comment]
> If one day we will move the docs out in the future, these changes are necessary. You can make it `Working in progress` or something, and do the works you like.

Yeah, but for now no need to do something with this docs. First of all, need to begin from translate with Crowdin service, there are ton of work. Welcome!

And this PR I'll close and will delete docs from modules repo. Time time time, just time for discussions...

**Pull request closed without merging**
