### PR TITLE
Added `text_align` option.

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: https://github.com/theme-next/hexo-theme-next/pull/73, Roadmap

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by 1v9** [comment]
We need a expert CSS worker 😉

**Comment by sli1989** [comment]
Nothing know about css, but 👍

**Comment by stevenjoezhang** [comment]
@ivan-nginx How do you like options like this:
```
text-align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: justify
```

**Comment by ivan-nginx** [comment]
Yep. Seems good.

**Comment by stevenjoezhang** [comment]
Updated. I'll add the docs

**Comment by ivan-nginx** [comment]
Maybe not `justify` by default? What is default value for `text-align`?

**Comment by stevenjoezhang** [comment]
@ivan-nginx No need to concern about it, the default value doesn't change in this PR:
屏幕快照 2019-03-16 上午10 40 45
屏幕快照 2019-03-16 上午10 41 02

**Comment by ivan-nginx** [comment]
I know what there is no breaking change. I just suggest to think about justify by default and as for me, I always prefer turn off justify as on Desktop and for Mobiles too. I'm talking about `en` and `ru` languages, IDK how will better for `cn`.

**Comment by stevenjoezhang** [comment]
I'll add a notice in the docs, about the difference between those options.

**Pull request merged**
