### PR TITLE
Add bootcdn for katex and add docs about cdnjs blocked in China

### PR DESCRIPTION
**Pull request by wafer-li**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [x] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): N/A

## What is the new behavior?

Add new optionnal cdn for katex, and supplement docs about cdnjs is blocked in some parts of China.

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
  katex:
    # Use Katex 0.7.1 as default
    cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
    # For whose visitors are mostly in China
    #cdn: //cdn.bootcss.com/KaTeX/0.7.1/katex.min.css
    # If you want to try the latest version of Katex, use one below instead
    #cdn: //cdn.jsdelivr.net/katex/latest/katex.min.css

```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by wafer-li** [comment]
@ivan-nginx 
But in some regions, bootcss is pretty slow.

image

Test result comes from @tsanie 

In my opinion, the bootcss is just for Chinese people, it should not use as default.

**Comment by MartinKolarik** [comment]
@wafer-li you can use jsDelivr for both mathjax and katex - it's fast everywhere and works in China.

**Comment by ivan-nginx** [comment]
> jsDelivr

Example links can u give?

**Comment by wafer-li** [comment]
@ivan-nginx 
Maybe this:
```
cdn: //cdn.jsdelivr.net/npm/katex@0.7.1/dist/katex.min.css
```

**Comment by ivan-nginx** [comment]
I think need to do external scripts for this. Just like external plugins for local generation usage.

**Comment by MartinKolarik** [comment]
@ivan-nginx sorry, there already was 1 jsDelivr url in the config file so I assumed you knew about it:

https://cdn.jsdelivr.net/npm/katex@0.8.3/dist/katex.min.css
https://cdn.jsdelivr.net/npm/katex@0.8.3/dist/katex.min.js
https://cdn.jsdelivr.net/npm/mathjax@2.7.2/MathJax.js

You can find anything else at https://www.jsdelivr.com/

**Comment by wafer-li** [comment]
After a speed test, I think we could use the jsDelivr as default CDN.

1. The jsDelivr has the CDN license issued by China government

2. It is pretty fast in Japan and Los Angeles, maybe it does fast everywhere.

-----

Ping in Japan: 
image

Ping in Los Angeles:

image

And ping in China:

image

**Comment by wafer-li** [comment]
@MartinKolarik 
The jsdelivr link in katex is added by me.

And it seems an old version of jsdelivr link, although it still works.

**Pull request merged**
