### PR TITLE
Changes comparison for Release Drafter Bot

### PR DESCRIPTION
**Pull request by ivan-nginx**

### CODE REVIEW

**Comment by 1v9** [comment]
Let's wait for magic, tomorow?

**Comment by ivan-nginx** [comment]
What u mean?

**Comment by 1v9** [comment]
I mean new release 👀

**Comment by ivan-nginx** [comment]
Yeah, tomorrow. [Draft ready](https://github.com/theme-next/hexo-theme-next/releases), but bot have some lags...

**Comment by 1v9** [comment]
Actually yesterday I tested this feature on my  fork, it's cool. Firstly I think maybe there's a method to split PR title from `type`, but not found in its repo🤣

**Pull request merged**
