### PR TITLE
Fix affix bug

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Revert https://github.com/iissnan/hexo-theme-next/commit/12808375bed33801ef597640b2280711529bd1f2
Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A

- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
@zq-97 Could you please help to confirm whether this has fixed the problem: https://github.com/theme-next/hexo-theme-next/issues/846

**Comment by stevenjoezhang** [comment]
Revert https://github.com/iissnan/hexo-theme-next/commit/12808375bed33801ef597640b2280711529bd1f2

**Comment by hsiangfeng** [comment]
看到留言版，我一直在想分頁以及標籤頁面的留言版需要出現嗎?
一般使用者滿少會在這邊留言，大多都是在文章內部留言。

**Comment by stevenjoezhang** [comment]
同意，但分頁以及標籤頁面的`comments`默認是`true`

https://hexo.io/docs/front-matter

需要由Hexo解决

**Comment by hsiangfeng** [comment]
> 
> 
> 同意，但分頁以及標籤頁面的`comments`默認是`true`
> 
> https://hexo.io/docs/front-matter
> 
> 需要由Hexo解决
> 
> >  Hexo**[Front-matter](https://hexo.io/docs/front-matter.html)**Front-matter is a block of YAML or JSON at the beginning of the file that is used to configure settings for your writings. Front-matter is terminated by three dashes when written in YAML or three sem

目前我的作法是採用以下方式來決定要不要顯示留言板

```
{% set page_type = page.type === 'tags' || page.type === 'categories' %}
<div style="{%if page_type %} visibility:hidden; height:0px;{% endif %}">
{% include '_partials/comments.swig' %}
</div>
``

**Comment by Raincal** [comment]
鉴于现在已经移除了 IE 支持，要不要考虑一下用 `position: sticky` 替代 affix

**Comment by stevenjoezhang** [comment]
嗯，bootstrap也移除了affix支持：
https://v4-alpha.getbootstrap.com/migration/#components

**Comment by stevenjoezhang** [comment]
@hsiangfeng 谢谢。我已在`tags`和`categories`的`Front-matter`中设置了`commets: false`

**Comment by stevenjoezhang** [comment]
See also: https://github.com/iissnan/hexo-theme-next/pull/2180

**Comment by stevenjoezhang** [comment]
已实现 `position: sticky` 替代 affix https://github.com/next-theme/hexo-theme-next/commit/b9968b6be0a8b20be80adad185ee94d713672e52

**Pull request merged**
