### PR TITLE
Add post navigation display configuration

### PR DESCRIPTION
**Pull request by liolok**
## PR Checklist 

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Theme displays post navigation (previous post and next post) in post footer by default.

## What is the new behavior?

Theme displays post navigation (previous post and next post) in post footer by default, and provides an option to turn it off.

### How to use?

In NexT `_config.yml`:
```yml
...
post_navigation: true # set it to false to disable navigation display
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by jiangtj** [comment]
> Please, no more useless options. Please.

我不认为这是个无用的选项，因为上下页的功能是内置，提供选项禁用也是合理的（虽然可能很少有人用到）.....

I don't think it's a useless option, because the functions of the previous and next pages are built-in, and it's reasonable to provide option disable (although it may be rarely used)

**Comment by stevenjoezhang** [comment]
> 因为上下页的功能是内置，提供选项禁用也是合理的

「内置」和「提供选项禁用」没有任何逻辑关联哦。如果坚持要加，就找一个比它更加「很少有人用到」的功能从`_config.yml`中删除。

**Comment by stevenjoezhang** [comment]
思考再三，我仍然看不出这个选项有任何用处。作为一个开源主题，用户拥有修改源码的自由，这就足够按自己的喜好实现功能了。诸位应该清楚的认识到，NexT主题1000多行配置就是由于过去几年中过于纵容用户，将许多与NexT主题无关的内容强行加进来，甚至不止一次的给Hexo背锅。如果可以的话，让Hexo出一个`post_navigation` helper，最好还能支持调整左、右，我举双手赞成。
以上。

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/theme-next/hexo-theme-next/commit/14172486dfb480aa80d467592963f57cc0bb734d

**Pull request closed without merging**
