### PR TITLE
Add pangu.js instead of auto_spacing in hexo

### PR DESCRIPTION
**Pull request by sli1989**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

To use auto spacing in hexo, you need to `$ npm install hexo-filter-auto-spacing --save` and `auto_spacing: ture`. but there are [many issues](https://github.com/hexojs/hexo-filter-auto-spacing/issues) using `hexo-filter-auto-spacing` in some special circumstance like chinese and english  headlines.

Issue Number(s): [#4](https://github.com/hexojs/hexo-filter-auto-spacing/issues/4), [#5](https://github.com/hexojs/hexo-filter-auto-spacing/issues/5), [#1608](https://github.com/iissnan/hexo-theme-next/issues/1608), [#27](https://github.com/hexojs/hexo-renderer-marked/issues/27)

## What is the new behavior?

I recommend to use the [pangu.js](https://github.com/vinta/pangu.js) to realize the auto spacing. `$ npm install pangu --save` seems to be not working. I need to add the js in `\themes\next\layout\_layout.swig`

- It seems just a need for environment in chinese and english.
-  If you have already  installed the [hexo-filter-auto-spacing](https://github.com/hexojs/hexo-filter-auto-spacing) in your local files, you must `npm uninstall hexo-filter-auto-spacing` firstly.
- Then you can set `auto_spacing: false` in your root `_config.yml` , or just comment it.

* Link to demo site with this changes: http://saili.science/2017/04/02/github-for-win/

### Files modified:

1.	`\themes\next\layout\_layout.swig`

-  add `<script src="https://cdnjs.cloudflare.com/ajax/libs/pangu/3.3.0/pangu.min.js"></script>` in   `<head>`
- add `<script>pangu.spacingPage();</script>` in `<body>`

### CODE REVIEW

**Comment by sli1989** [comment]
however, I am a little white.

**Comment by wafer-li** [comment]
……

You could take my #32 PR as a reference, and please provide a config for it.

----

Besides, `little white` is Chinglish. You should say that you know little about swig.

**Comment by sli1989** [comment]
😂 haha...
Perhaps i have no time and no energy to do it. i will try it...

**Comment by wafer-li** [comment]
If you don't have time for it.

I could just implement it, but I need tests for Muse | Mist scheme since I don't use those schemes.

**Comment by sli1989** [comment]
it would be good.
i can run test.

**Comment by ivan-nginx** [comment]
And what mean `auto spacing` can u show it? I just don't see what this it.

**Comment by wafer-li** [comment]
@ivan-nginx 

Working on it, I am now writing a test page.

> And what mean auto spacing can u show it? I just don't see what this it.

Just add spaces between Chinese and English word make it more beautiful, like this:

```
# Original
你hello好

# After
你 hello 好
```

**Comment by ivan-nginx** [comment]
So, this is for Chines only? I think need to create separated repo with lib for this.

**Comment by wafer-li** [comment]
@ivan-nginx 

> So, this is for Chines only? I think need to create separated repo with lib for this.

OK, I am just going to discuss this with you.

For now I am just finishing porting from this PR.

When I finish, I will try to implement the separated lib way.

**Comment by sli1989** [comment]
maybe mixed language situation...

**Comment by ivan-nginx** [comment]
As i right understand, in Chinese language there are no spaces to use? Letters write together always?

**Comment by wafer-li** [comment]
@ivan-nginx 
Yes, Chinese language doesn't have spaces, just have paragraph and punctuations.

We use the knowledge of the language and our experiences to determine what is so-called "word" in the English world which separated by space.

**Comment by ivan-nginx** [comment]
Alright, then need to created separated lib for that. This pull resumed in #56.

**Pull request closed without merging**
