### PR TITLE
Add english support for Valine comments

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [ ] No.

### CODE REVIEW

**Comment by 1v9** [comment]
Is 'zh-cn' default value?

**Comment by stevenjoezhang** [comment]
Yes, only two available values😂

**Comment by ivan-nginx** [comment]
@stevenjoezhang same question as above: why `zh-cn` by default if default language anywhere is `en`?

**Comment by 1v9** [comment]
@ivan-nginx https://valine.js.org/en/i18n.html

**Comment by ivan-nginx** [comment]
@1v9 I see. 2 build-in languages: `en` and `cn`. I don't understand why @stevenjoezhang set `cn` by default? Go `ru` language by default on `creative_commons`? Or for `yandex_site_verification` we will write comments above:

```diff
-# Yandex Webmaster tools verification setting
-# See: https://webmaster.yandex.ru
+# Настройки верификации Вебмастер-панели Яндекса
+# Смотрите: https://webmaster.yandex.ru
```
It is unacceptable.

Even Hexo have `en` language by default. Everywhere `en` language by default.
This. Is. **International.** Language.

**Comment by stevenjoezhang** [comment]
@ivan-nginx  The reason is that leancloud, one of the major dependencies of valine, doesn't provide English webpage nor documentation. I believe most users of leancloud or valine are not English speakers. See: https://medium.com/leancloud/getting-leancloud-ready-for-the-english-speaking-audience-97793bb413f1

And it's not hard to make English default language, just need to modify `layout/_third-party/comments/valine.swig`

**Comment by ivan-nginx** [comment]
I suggest 2 way-outs:

1. lang: '{{ theme.valine.language }}' || 'zh-cn' → 'en'
2. As we can see [here](https://theme-next.org/docs/third-party-services/comments-and-widgets/index.html#Valine) — screenshoots on `cn` lang, LC on `cn` too. So, then need to write [title](https://theme-next.org/docs/third-party-services/comments-and-widgets/index.html#Valine)  something like that: Valine (China)

**Pull request merged**
