### PR TITLE
Refactor js cdn to support jsdelivr

### PR DESCRIPTION
**Pull request by jiangtj**
## PR Checklist 

- [x] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the new behavior?
Load js file from cdn
image

### How to use?
In NexT `_config.yml`:
```yml
# If want to use jsdelivr, you can set it as follow
js: https://cdn.jsdelivr.net/gh/theme-next/hexo-theme-next@${version}/source/js/${file}
```

## Does this PR introduce a breaking change?
- [x] Yes.
- [ ] No.

```diff
- js: js
+ # set js cdn
+ # ${version} will be replaced by next-version e.g. 7.6.0
+ # ${file} be replaced by file name e.g. next-boot.js
+ # if you want to use jsdelivr, can config as follow (should use release version, not master)
+ # js: https://cdn.jsdelivr.net/gh/theme-next/hexo-theme-next@${version}/source/js/${file}
+ js: js/${file}
```

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/theme-next/hexo-theme-next/pullRequest?prid=4669928&bid=15629022)

**Comment by jiangtj** [comment]
I learned that some people use `js` to configure cdn, and will redesign the configuration file later. Maybe BC
```yml
js: js
```

**Comment by ivan-nginx** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/theme-next/hexo-theme-next/pullRequest?prid=4669928&bid=15629022)

**Comment by stevenjoezhang** [comment]
The configuration file does need to be redesigned. If possible, move all vendor settings from `_config.yml` to some other location

**Comment by jiangtj** [comment]
Add perf test script for zero config hexo site, and `String.replace`. It seems work fine.

I think we shouldn't introduce performance issues at zero configuration, this is the hardest to troubleshoot.
If it happens when a feature is enabled, we can easily deal with it.

**Comment by stevenjoezhang** [comment]
I suggest not to fork or create new repository under the theme-next organization. None of us have permission to delete them.

**Comment by jiangtj** [comment]
> I suggest not to fork or create new repository under the theme-next organization. None of us have permission to delete them.

Understand, temporarily close, split and improve the code for performance testing, wait

**Comment by stevenjoezhang** [comment]
See also https://github.com/next-theme/hexo-theme-next/commit/ae21b8b8e00603dd2690d9cb31f92ddf2bf7647d

**Pull request closed without merging**
