### PR TITLE
Allow delayed loading of three.js

### PR DESCRIPTION
**Pull request by 1v9**
See #932

### CODE REVIEW

**Comment by 1v9** [comment]
In fact I have seen too much blogs based on Github Pages enable features like three.js and they all sucks because the network condition between Github CDN and China is a mess.

To avoid blocking render, I thought of three ways:

* use hexo filter to operate DOM and put `<script>` in the bottom.

* modify the position of `<script>` in our swig template.

* use JavaScript, like this PR.

Surely this PR is not good enough, for wider use maybe hexo filter is best.

**Comment by jiangtj** [comment]
How about `defer` in script?
http://www.w3school.com.cn/tags/att_script_defer.asp

**Comment by 1v9** [comment]
@jiangtj 

Yeah that's another method (before **Domcontentloaded**) but **async** is wrong.

```html
<script defer src="/path/to/three.min.js"></script>
<script defer src="/path/to/three-waves.min.js"></script>
```

**Comment by 1v9** [comment]
`  {% include '_scripts/three.swig' %}` or `  {% include '_thied-party/three.swig' %}` or other position?

**Pull request merged**
