### PR TITLE
Create Awesome list

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [x] Other... Please describe:

## What is the current behavior?

Issue resolved: #758

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by jiangtj** [comment]
I think created a new repo, maybe better.

**Comment by 1v9** [comment]
Move `## Third party applications` to standalone repo.

**Comment by stevenjoezhang** [comment]
@jiangtj @1v9 Do you have any suggestions for naming the new repo? e.g. awesome-theme-next ?

**Comment by jiangtj** [comment]
awesome-theme-next or awesome-next 😂 I prefer the latter.

**Comment by sli1989** [comment]
what's the meaning of `Third party applications` in Next 
😢

**Comment by stevenjoezhang** [comment]
Commit related to `Third party applications`:
https://github.com/theme-next/hexo-theme-next/commit/8cedfbca078fbd32edb18ea68c7820d0887b6e9f#diff-04c6e90faac2675aa89e2176d2eec7d8
😢

**Comment by jiangtj** [comment]
https://github.com/theme-next/hexo-theme-next/pull/868 If plug-in, then plug-in can be used as a kind of resource to put here?
And the blog using NexT can also be put here.

**Comment by stevenjoezhang** [comment]
Good idea. I will collect more on this

**Comment by stevenjoezhang** [comment]
@1v9 @jiangtj @sli1989 
https://github.com/theme-next/hexo-theme-next/tree/readme
https://github.com/theme-next/hexo-theme-next/tree/readme/docs/zh-CN
https://github.com/theme-next/hexo-theme-next/tree/readme/docs/ru
https://github.com/theme-next/hexo-theme-next/blob/readme/docs/AUTHORS.md

**Comment by 1v9** [comment]
@stevenjoezhang AUTHORS.md is cool but scheme preview spices my eyes, maybe simple link to theme-next.org?

**Comment by stevenjoezhang** [comment]
Do you mean link to theme-next.org in https://github.com/theme-next/awesome-next/blob/master/README.md ?

**Comment by 1v9** [comment]
@stevenjoezhang No I was talking about previews in README.md files.

**Comment by stevenjoezhang** [comment]
屏幕快照 2019-07-09 下午3 47 50
I think this one is good enough

**Comment by stevenjoezhang** [comment]
@1v9 about preview... I think this image looks fine

**Comment by stevenjoezhang** [comment]
Able to merge now?

**Comment by stevenjoezhang** [comment]
@1v9 Live previews added

**Comment by 1v9** [comment]
@stevenjoezhang Do we need  political correctness?

**Comment by stevenjoezhang** [comment]
next2

**Comment by stevenjoezhang** [comment]
next2

Able to merge now?

**Comment by ivan-nginx** [comment]
@stevenjoezhang Can we do multilingual support for that preview?

image

2, 4  - on CN, but Language EN setted in Github. Same with RU lang.

image

**Comment by stevenjoezhang** [comment]
> I mean all 4 screen must be on selected language in Github.

It's hard to do so - 12 screenshots and 3 photoshop projects. I think this one is OK for multilingual support for the preview:

next-new

**Comment by ivan-nginx** [comment]
> It's hard to do so - 12 screenshots and 3 photoshop projects. 
Why 12? Just 3 screenshots in result. Can u provide which service u use?

**Comment by stevenjoezhang** [comment]
macOS can only take screenshot of one window at a time (png with alpha channel), so have to use photoshop to combine screenshot of 4 schemes into 1. Maybe this process can also be done in an automated way...

**Comment by ivan-nginx** [comment]
I think must be automatic services for that.

**Pull request merged**
