### PR TITLE
Native Dark Mode support

### PR DESCRIPTION
**Pull request by stevenjoezhang**
Thanks to @1v9 @BillYang2016 and @Yuhhang, this Pull Request was inspired by your dark mode design and implementation.

Some stylus variables are exported as CSS variables, and will no longer be available during customization.

> Hello darkness my old friend.
> I've come to talk with you again.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
- [x] Currently, the color of pagination has not been replaced.

https://github.com/1v9/hexo-next-nightmode/blob/a0b95c098a7476ba18c9b3c80487736678d13724/css/scheme.styl#L68-L72

- [x] And the color of the buttons under Pisces / Gemini needs to be adjusted.

- [x] Need more testing.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/1v9/hexo-next-nightmode">1v9/hexo-next-nightmode</a></strong></div><div>Add Night Mode support for NexT. Contribute to 1v9/hexo-next-nightmode development by creating an account on GitHub.</div></blockquote>

**Comment by asdf2014** [comment]
@stevenjoezhang Can we add a button to switch dark mode?

image

**Comment by stevenjoezhang** [comment]
@asdf2014 Use this plugin: https://github.com/sandoche/Darkmode.js

**Comment by asdf2014** [comment]
@stevenjoezhang Thanks a lot. It worked. https://yuzhouwan.com/

5DD2BFD5-3035-49A0-B232-2CB4D61EE614

**Comment by FgSurewin** [comment]
> @stevenjoezhang Thanks a lot. It worked. https://yuzhouwan.com/
> 
> 5DD2BFD5-3035-49A0-B232-2CB4D61EE614
> 
> >  宇宙湾**[宇宙湾](https://yuzhouwan.com/)**Benedict Jin's Blog

Could you mind sharing how to how to use that dark button plugin? As I am new to hexo, I don't know how to insert a js file into swig file.

**Comment by wangzhe3224** [comment]
Can we set a force dark mode instead of dark mode depending on user's system theme? Because it seems dark mode is no activated even I use a dark theme in Ubuntu 19. Thanks

**Comment by stevenjoezhang** [comment]
Sorry, we have no plans to add this feature.

**Pull request merged**
