### PR TITLE
not only post can show

### PR DESCRIPTION
**Pull request by Mryan2005**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by Mryan2005** [comment]
@stevenjoezhang

**Comment by stevenjoezhang** [comment]
Thanks for your contributing. The `{% if %}` tag is not closed, so you will get an error message when building.
**And, you only modified the code for livere.** So this PR may not match your own expectations.

**Comment by Mryan2005** [comment]
> Thanks for your contributing. The `{% if %}` tag is not closed, so you will get an error message when building.
> **And, you only modified the code for livere.** So this PR may not match your own expectations.

SO....

**Comment by Mryan2005** [comment]
I SEE

**Comment by Mryan2005** [comment]
but now

**Comment by Mryan2005** [comment]
@stevenjoezhang

**Comment by stevenjoezhang** [comment]
So, what's the difference between your code and `{% if page.comments or is_post() %}`?

**Comment by jiangtj** [comment]
is_post()?  post articles are all show this comment without close?

As far as I know, page.comments defaults to true. You can choose to close.

**Comment by 1v9** [comment]
What's this PR for?

**Pull request closed without merging**
