### PR TITLE
Add comment count in mobile

### PR DESCRIPTION
**Pull request by sli1989**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

The comment count in mobile doesn't display. It's a necessary meta, so display it without a enable option.

Issue Number(s): #180

## What is the new behavior?
Add the count meta in post.

* Screens with this changes: 

before

after

* Link to demo site with this changes: http://test.saili.science/2018/03/17/hello-world/

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by LEAFERx** [comment]
recommend to add switch in _config.yml post meta

**Comment by ivan-nginx** [comment]
I still can't understand why it was added to disabled by default? Trafic economy or what? What's the reason?

**Comment by LEAFERx** [comment]
dont know either

**Comment by sli1989** [comment]
All tested. The screenshots are added.

**Comment by sli1989** [comment]
> recommend to add switch in _config.yml post meta
I think it's a necessary meta.

**Comment by ivan-nginx** [comment]
Comments system? All tested? Again: need to try why it was added to disabled by default?
If all fine, that's good. But if not? Need to test it carefully. I don't think what it was maded by Vi simply for trafic economy or something like that.

**Comment by sli1989** [comment]
OK, more comment systems would be tested.

**Comment by sli1989** [comment]
Gitment comment system works fine. The comment count display with Disqus in homepage but not in post page. Check this [demo](http://test.saili.science/2018/03/17/hello-world).

**Comment by ivan-nginx** [comment]
Disqus appear not instantly at most time and for now i see comments count in homepage and in post page too. So, i think it's fine.

**Comment by sli1989** [comment]
OK, I doesn't use disqus. It seems all fine.

**Pull request merged**
