### PR TITLE
Load velocity only if motion is enabled

### PR DESCRIPTION
**Pull request by maple3142**
## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
`velocity` is added in site even if `motion.enable` is false

Issue Number(s): N/A

## What is the new behavior?
`velocity` only added if `motion.enable` is true

* Screens with this changes: N/A
* Link to demo site with this changes: https://blog.maple3142.net/

### How to use?
No need to change anything.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by tsanie** [comment]
There is a problem, that the sidebar in Must/Mist is now hard-code dependent on the velocity. So need to refactor the `motion.js` first...

**Comment by maple3142** [comment]
Or change it to another option?
Like `disable_velocity`, and warn user about Must/Mist theme and motion depends on velocity.

**Comment by ivan-nginx** [comment]
No. i think no need to add extra options here, but about warn to Mist/Muse nice idea.
Ans as Tsanie talk above, need to refactor this somehow. To external repo maybe.

So, this sill be merged? Let's wait another maintainers vision about this.

**Comment by wafer-li** [comment]
That is similar to the "turn off js" problem.

agree with @ivan-nginx 
I think showing the warning is enough.

**Comment by sli1989** [comment]
So, add annotation in `_config.yml`?

**Comment by geekrainy** [comment]
Caused by click button did not respond.
https://github.com/theme-next/hexo-theme-next/blob/ca2554bcfe766a01def2cb723c52a020d94a2060/source/js/src/utils.js#L113

**Comment by stevenjoezhang** [comment]
Superseded by #951

**Pull request closed without merging**
