### PR TITLE
Fix known issues

### PR DESCRIPTION
**Pull request by 1v9**
Issue resolved: #1213

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
What's the difference?

**Comment by 1v9** [comment]
if disable social_icons, will get undefined

**Comment by stevenjoezhang** [comment]
else set icon = ''
It can be done with only two lines. Try it.

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/pull/1219#issuecomment-543172183

**Pull request merged**
