### PR TITLE
Update docs for DATA-FILES

### PR DESCRIPTION
**Pull request by stevenjoezhang**
Pending Hexo v4.3 release.

### CODE REVIEW

**Comment by sli1989** [comment]
can `docs` be removed, and consist with org repo?

**Comment by stevenjoezhang** [comment]
org repo does not have Chinese documentation, maybe we need to start translation work first.

**Comment by sli1989** [comment]
well, i can working on it.

**Comment by stevenjoezhang** [comment]
https://theme-next.js.org/docs/getting-started/configuration.html

**Pull request closed without merging**
