### PR TITLE
Add contributing.md in EN&CN lang

### PR DESCRIPTION
**Pull request by sli1989**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [ ] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes have been added (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [X] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [X] Documentation content changes.
- [ ] Other... Please describe:

Add contributing.md in EN&CN lang.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [X] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
«Sqash and merge» to split all current commits into 1 commit.

**Comment by sli1989** [comment]
Any suggestions? some update in hyperlink haven't been pushed.

**Comment by ivan-nginx** [comment]
1. Remove 
    image
   Looks like childly.
2. Add RU flag, i'll translate it.
3. Add to console code(s) (`$ git add`, etc.) bash? Or sh. (\```bash)

**Comment by sli1989** [comment]
> Add to console code(s) ($ git add, etc.) bash? Or sh. (```bash)

I don't understand...

> Maybe change H1 to H2 for all headers.

change H1 to H2, H2 to H3?

**Comment by ivan-nginx** [comment]
> change H1 to H2, H2 to H3?

Yes, just move down at 1 step headers hierarchy.

> I don't understand...

Here is simple codeblock example:

```
$ git add .
$ git commit -m "add commit messamge"
$ git push origin patchname
```

And here is codeblock with bash syntax highlighting:

```bash
$ git add .
$ git commit -m "add commit messamge"
$ git push origin patchname
```

**Comment by sli1989** [comment]
oh, got it.

**Comment by ivan-nginx** [comment]
Yeah, looks nice. :+1:

**Comment by sli1989** [comment]
I know nothing about «Code of conduct», it's a management and law-related problem..😅

**Comment by ivan-nginx** [comment]
I think there are exists templates in other OS projects with this document.
Ok, it's fine, Squash & Merge it.

**Comment by sli1989** [comment]
if it's fine to fuse and reference other templates, i maybe can do it later.

**Pull request merged**
