### PR TITLE
Change lockLabel

### PR DESCRIPTION
**Pull request by 1v9**
#786, addition to #782.

### CODE REVIEW

**Comment by 1v9** [comment]
@ivan-nginx [mergeable.yml](https://github.com/theme-next/hexo-theme-next/blob/master/.github/mergeable.yml#L21) should update, we can't pass check now 😂

**Comment by ivan-nginx** [comment]
How about add 🔒 icon? Copy from [here](https://www.emojicopy.com/).

**Comment by 1v9** [comment]
> How about add 🔒 icon? Copy from [here](https://www.emojicopy.com/).

Nice

**Comment by ivan-nginx** [comment]
> @ivan-nginx [mergeable.yml](https://github.com/theme-next/hexo-theme-next/blob/master/.github/mergeable.yml#L21) should update, we can't pass check now 
> 
>  Must be in the "feat|imp|fix|doc|chore" project.
> Input : Feats. / Imprs. / Fixes,Detected Bugs,Requested Features,Offered Improvements
> Settings : {"do":"project","no_empty":{"enabled":true},"must_include":{"regex":"feat|imp|fix|doc|chore"}}

This is a little bug: bot not triggered with «Projects» switch. If u check/uncheck label or Milestone, for example, bot will accept Projects.

**Comment by 1v9** [comment]
🔒

or

🔒 Locked

**Comment by ivan-nginx** [comment]
Wait, I'll do something...

**Comment by 1v9** [comment]
Wait again, issue also has options...

**Pull request merged**
