### PR TITLE
Force HTTPS of `google-analytics.swig`. Again.

### PR DESCRIPTION
**Pull request by hsiangfeng**
No "https" will result in an error。

## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by 1v9** [comment]
What's the error?

**Comment by ivan-nginx** [comment]
I think there is no error because auto-protocol must be used. But need to test it: can GA use link without schema or not?

**Comment by hsiangfeng** [comment]
會有機率無法取得GA。

建議直接使用"https"，因為有時候會變成"http"

**Comment by hsiangfeng** [comment]
The organic rate will not be able to obtain GA.

It is recommended to use "https" directly because it sometimes becomes "http"

**Comment by ivan-nginx** [comment]
What's this «it sometimes becomes "http"»? If site proto http, http will be used; if https, will be used https. All another similar 3rd-party services working like that. I think if protocol of website will be **http**, GA with your changes (**https**) will not work.
Can u provide more info about that GA usage recommendations?

**Comment by Raincal** [comment]
https://google.github.io/styleguide/htmlcssguide.html#Protocol

**Comment by ivan-nginx** [comment]
Seems fonts need to be fixed too:

https://github.com/theme-next/hexo-theme-next/blob/d78a4008c7b97612cea0c49ee20d6730b82c32ff/layout/_partials/head/external-fonts.swig#L47

**Pull request merged**
