### PR TITLE
New README for NexT

### PR DESCRIPTION
**Pull request by ivan-nginx**
Services used:

* [Screens for responsive devices](https://techsini.com/multi-mockup/index.php) 
* [Gifs from screens](https://gifmaker.me/)

### CODE REVIEW

**Comment by 1v9** [comment]
#1141

**Comment by ivan-nginx** [comment]
So? U can make 3 languages and update this pull.

**Comment by ivan-nginx** [comment]
But I don't think what needed 3 screens because website content not multilanguage for now.

**Comment by 1v9** [comment]
Just a note, for now I think its better than before.

**Comment by stevenjoezhang** [comment]
> for now I think its better than before

Sorry, I don't

**Comment by stevenjoezhang** [comment]
In fact, gif is not a good idea. It's neither elegant nor powerful. Especially using the picture of iPhone4 in 2019.

**Comment by jiangtj** [comment]
Use this instead of the native for flat-square?  But I didn't find localized badge.
图片
图片
图片

**Comment by stevenjoezhang** [comment]
@jiangtj Do you have any idea how to make this badge work?
```
https://img.shields.io/github/downloads/theme-next/hexo-theme-next/total?style=flat-square
```

**Comment by 1v9** [comment]
https://img.shields.io/github/contributors/theme-next/hexo-theme-next?style=flat-square
https://img.shields.io/github/release-date/theme-next/hexo-theme-next?style=flat-square

**Pull request merged**
