### PR TITLE
Drop cheerio

### PR DESCRIPTION
**Pull request by stevenjoezhang**

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/hexo-theme-next/hexo-theme-next/pullRequest?prid=4603935&bid=15449114)

**Comment by ivan-nginx** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/hexo-theme-next/hexo-theme-next/pullRequest?prid=4603935&bid=15449114)

**Comment by 1v9** [comment]
We never have any test case but seems everything's ok 😘

**Comment by maple3142** [comment]
I wonder why replace cheerio with regex..?

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/pull/3850

```diff
"dependencies": {
-    "cheerio": "0.22.0",
  },
  "devDependencies": {
+    "cheerio": "0.22.0",
  }
```

**Comment by maple3142** [comment]
But... use regex to handle html? Why not just a use another html parser or similar tools such as jsdom or other lightweight alternative?
Regex shouldn't be used to parse html for any serious purpose.

**Comment by stevenjoezhang** [comment]
> Why not just a use another html parser or similar tools such as jsdom or other lightweight alternative?

Please note: Currently the theme is installed via `git clone` instead of `npm install`. Using any non-Hexo dependent package will get the same result: `Error: Cannot find module xxx`

**Comment by jiangtj** [comment]
另一个方案是，重写md渲染器
优点：更快
缺点：特定的功能模块只能使用内置的md渲染器，维护成本增加

比如：https://github.com/jiangtj/hexo-theme-cake/pull/28  提供了`disable_cake_marked`禁用内置的md渲染，但禁用后，图片懒加载功能失效

**Comment by stevenjoezhang** [comment]
维护一个主题已经很累了。渲染器不关我的事，谁爱管谁管。

**Comment by jiangtj** [comment]
> 维护一个主题已经很累了。渲染器不关我的事，谁爱管谁管。

😂 这几天在研究这个，hexo如果只用一个固定的md渲染器，整体性能应该能提高至少50%

**Comment by stevenjoezhang** [comment]
确实如此，而且像 hexo-renderer-kramed 这种已经几年没更新了 https://www.npmjs.com/package/hexo-renderer-kramed 有兴趣的话可以发邮件给npm接手这个包。
如果Hexo的渲染器有插件的接口，并且给主题调用的方法，那么就可以高效地解决问题。但这还没有被纳入Hexo的标准，有兴趣的话可以向Hexo提一下建议。

**Pull request merged**
