### PR TITLE
Feature: Close sidebar when click any blank part (#606)

### LINKED ISSUE #606: close sidebar when click any blank part
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
can it possible to add a new feature about closing sidebar while click blank area? 

### Actual behavior 
right now, it can only be done by clicking the "sidebar-toggle" button at the lower right.

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
node: 11.7.0
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [x] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved #606

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Yes, only for Muse | Mist. And I think an extra option in `_config.yml` is not necessary. The new behavior is that:
- On desktop platform, if the sidebar is opened, you can continue reading by scroll down the page; and you can close it by click any blank part
- On mobile platform, it's the same as current behavior, `sidebar-dimmer` was first introduced in https://github.com/iissnan/hexo-theme-next/commit/3a3b864f6616f89aaa0c1e92ed0b9f98bd96daf1

**Comment by ivan-nginx** [comment]
> * On desktop platform, if the sidebar is opened, you can continue reading by scroll down the page; and you can close it by click any blank part

Some peoples like to read and allocate text. So, sidebar will also closed out and TOC will not have weight.

**Comment by stevenjoezhang** [comment]
Ahh, that's right, I'll add an option to let users decide how the sidebar works

**Comment by ivan-nginx** [comment]
Also, can u add docs in [NexT website](https://theme-next.org/docs/) how to use this feature?

**Pull request merged**
