### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by ivan-nginx**
Enjoy!

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Why was gitment translation added back?

**Comment by ivan-nginx** [comment]
IDK, u know this is automatically. After comments merged?

**Comment by ivan-nginx** [comment]
Ok, here is latest changes: https://github.com/theme-next/hexo-theme-next/commit/541e47748df71d11c591769935f0ac645f046335#diff-4836f5d6c67b4dd811a773abf1b66cd7

**Comment by ivan-nginx** [comment]
https://crowdin.com/translate/theme-next/all/en-fr#h=5648d7fb4f1ea9a69fd10fccacd7d007290033

I don't understand why...

**Comment by ivan-nginx** [comment]
image

Are u deleted this string, right? This string no needed?

**Comment by stevenjoezhang** [comment]
Yes, it's strange 🤔

**Comment by stevenjoezhang** [comment]
https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

**Pull request merged**
