### PR TITLE
feat($layout/page.swig): cutstom new layout of page

### PR DESCRIPTION
**Pull request by jingxinxin**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [X] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [X] Tests for the changes was maked (for bug fixes / features).
   - [X] Muse | Mist have been tested.
   - [X] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [X] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Cutstom new layout of page

Issue resolved: N/A

## What is the new behavior?

Cutstom new layout of page
- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
custom_file_path:
    page:
      url: source/_data/study.swig
      type: study
      script: study.js
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [X] No.

### CODE REVIEW

**Comment by 1v9** [comment]
Implementing only one custom page type is not good.
Support more custom page types or create a new page type completely.
Also you need to sign upstairs CLA and prepare docs for this feature.

**Comment by stevenjoezhang** [comment]
This feature seems unnecessary...

**Comment by jingxinxin** [comment]
> Implementing only one custom page type is not good.
> Support more custom page types or create a new page type completely.
> Also you need to sign upstairs CLA and prepare docs for this feature.

@1v9 yep，It's just a sudden idea I had when I was expanding the page, and I immediately came up with it. Customizing multiple pages is definitely needed.
@stevenjoezhang Mainly I want to ensure the purity of the original library. I don't want to modify the files in theme path.
At the same time, I can also expand the pages.

**Comment by stevenjoezhang** [comment]
@jingxinxin We can use a survey to determine how many users need this feature. People who aren't as good at programming as you are may be confused by this feature.

**Comment by stevenjoezhang** [comment]
Thanks for your contributing. Custom new layout of page is a high-end feature that requires a lot of template changes to allow users to implement their ideas. There is no point in trying to use a generic solution.

**Pull request closed without merging**
