### PR TITLE
Using Template literals (Template strings)

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [ ] Feature.
- [x] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): N/A

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
Maybe we push this changes only in v7.x? Because ES2015 needed to compatability with template literals, as I see from docs.

**Comment by ivan-nginx** [comment]
Now need to create a plan for:

1. Master branch – all changes.
2. v6.x branch – only fixes / optiomizations.
3. v7.x branch – fixes / optiomizations / features.

Need to create new issue with suggests on it.

**Comment by ivan-nginx** [comment]
If all done here, «Squash and merge».

**Comment by stevenjoezhang** [comment]
Done

**Comment by maple3142** [comment]
@stevenjoezhang Is there any reason to use template literals in client side script without babel? 
Wouldn't it break old browser without es6?

**Comment by ivan-nginx** [comment]
@maple3142 it seems IE only not support literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Browser_compatibility

**Comment by stevenjoezhang** [comment]
@maple3142 I don't think it's a problem. ES6 was released about 4 years ago:

The only problem is IE, and bloggers can use v6.x if really want to support it.
For older browsers, like IE8 or safari on iOS4, I think this update won't break them, because they have already been broken by HTML5 and  CSS3.
What's your opinion?

**Comment by maple3142** [comment]
The problem is `uglify-js` only support es5, which will cause my blog unable to minify javascripts in the future.

**Comment by ivan-nginx** [comment]
`uglify-js` used in [hexo-filter-optimize](https://github.com/theme-next/hexo-filter-optimize)?

**Comment by stevenjoezhang** [comment]
Hope this would help: https://github.com/mishoo/UglifyJS2/issues/3285

**Comment by maple3142** [comment]
@ivan-nginx I don't use it, because I use  my own [build script](https://github.com/maple3142/Blog/blob/master/gulpfile.js) instead.

@stevenjoezhang I know that es6-aware minifiers does exist, but why do NexT need to use template literals?
In my opinion, I think that both using pure es5 and es6+babel is good.

**Comment by ivan-nginx** [comment]
So, mb cleant-side scripts don't need literals?

**Comment by ivan-nginx** [comment]
@maple3142 reverted via #590.

**Comment by stevenjoezhang** [comment]
Revert reverted via #1023.

**Pull request merged**
