### PR TITLE
Update valine comment system version

### PR DESCRIPTION
**Pull request by xCss**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): N/A

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes: N/A
* Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
valine:
    ...
    visitor: false # Article reading statistic https://valine.js.org/visitor.html
...
```

## Does this PR introduce a breaking change?
- [x] Yes.
- [ ] No.

### CODE REVIEW

**Comment by sli1989** [comment]
Can this share the same class `Counter` in [former LeanCloud visitor count](https://notes.wanghao.work/2015-10-21-%E4%B8%BANexT%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD.html#%E9%85%8D%E7%BD%AELeanCloud). If this do, the change maybe more smooth.

**Comment by xCss** [comment]
@sli1989 
Yes, now it's the previous `Counter` class in [former LeanCloud visitor count](https://github.com/theme-next/hexo-theme-next/blob/master/docs/LEANCLOUD-COUNTER-SECURITY.md)

**Comment by sli1989** [comment]
everything is fine. but seems if the view=0, there is blank view instead of `0` in meta. after clicking the post, the `xid` item was created, then the counter increase.

qq 20180708143549

**Comment by xCss** [comment]
@sli1989 ，`xid` is currently a redundant field.
And your blog is http://saili.science/2018/06/24/cost-function/
I see the statistics on your blog are normal.

**Comment by sli1989** [comment]
that's because i clicked the post. I mean the view=0 situation.

**Comment by xCss** [comment]
@sli1989 
For `view=0` or `no view record`, there is fault tolerance, All set to `0`

**Comment by ivan-nginx** [comment]
@xCss So, Valine will count visitors? It's current visitors counting (like was in HyperComments) or total counting for post (this function already exists in NexT, right?)

**Comment by xCss** [comment]
@ivan-nginx Yes, Valine has been able to count visitors, But this feature is optional.

The original NexT already contains this method, I think we need to give users more choices.

**Comment by ivan-nginx** [comment]
@xCss so, for count visitors option user need to be loggen in Valine? I mean how about [LC Security Plugin](https://github.com/theme-next/hexo-leancloud-counter-security)?

**Comment by xCss** [comment]
@ivan-nginx Sorry, Valine can't call `_config.yml`, but I think Valine can solve the security problem with the leancloud cloud engine. [Follow these steps](https://leaferx.online/2018/02/11/lc-security/).

**Comment by sli1989** [comment]
> For view=0 or no view record, there is fault tolerance, All set to 0

That's the problem, the view of new post is blank not the '0'...

**Comment by xCss** [comment]
@sli1989 , Sorry, the bug has been reproduced, this is my logical error.
 I'll fix it in the next version of Valine.
Thx.

**Comment by xCss** [comment]
@sli1989 In fact, the number of visits in the Valine will automatically create the class, and you don't need to manually create the `Counter` (of course you can create it manually)

There are no conflicts between the two methods, and `leancoud_visitors` have higher priority:
[#diff-d4f96cf2cea92b9d7c8d95bb034e2eb2R4](https://github.com/theme-next/hexo-theme-next/pull/345/files#diff-d4f96cf2cea92b9d7c8d95bb034e2eb2R4)
``` diff
- {% if theme.leancloud_visitors.enable %}
+ {% if theme.leancloud_visitors.enable and !theme.valine.visitor %}
```

**Comment by sli1989** [comment]
Oh, U mean valine visitor automatically creates the class `Counter`? Well, that's great.

**Comment by ivan-nginx** [comment]
@xCss @sli1989 i mean need to join this 2 counts in one, without confusing user. Docs or instructions maybe?

**Comment by sli1989** [comment]
>  i mean need to join this 2 counts in one

Maybe not, it's the way provided by valine comments. We can force users to use valine. But some intructions needed to be added in valine setting section in `_config.yml` or doc about valine comment in HELP.

**Comment by xCss** [comment]
@sli1989 @ivan-nginx Don't force users to choose. Other comment systems still need `leancloud_visitors`, and the count visitors in the Valine can be used as an alternative.

In fact, the Valine uses the same class `Counter` as `leancloud_visitor`, except that the Valine adds a redundant field `xid`, the other is exactly the same.

**Comment by ivan-nginx** [comment]
I mean that's cases:

1. If user use Disqus system and use internal LC (with or without LC Sec plugin), it's okay.
2. If user want to replace Disqus with Valine, but he still use internal LC (with or without LC Sec plugin), he can not turn on Count in Valine.
3. Same at above, but if he turn on Valine count then what? Will use Valine's counter with or without LC Sec plugin?

**Comment by sli1989** [comment]
> If user want to replace Disqus with Valine, but he still use internal LC (with or without LC Sec plugin), he can not turn on Count in Valine.
> Same as above, but if he turn on Valine count then what?

There seems a conflict about the sdk version (reinitiating problem with two version) when using  internal leancoud_visitors and valine comment at the same time. As said before, there are no conflicts between Counter class introduced by the two methods. This can be seen as redundant.

> Will use Valine's counter with or without LC Sec plugin?

Need @xCss to develop maybe.

**Comment by ivan-nginx** [comment]
> Need @xCss to develop maybe.

> i mean need to join this 2 counts in one, without confusing user

If it's possible, yes.

**Comment by LEAFERx** [comment]
> And the count visitors of the Valine is a private method, no external calls are provided.

@xCss 
But AppKey and AppId are still available for attackers. Attackers can init another AV object and modify Counter class, and maybe even contents of comments. It still need further ACL configuration. The LC Sec plugin makes the process of adding page item into db locally so that attackers cannot add their data by AV object. And we still need Leanengine to ensure the count number been updated in the right way, which is +1 every visit, since the ACL to anaymous must be `CAN UPDATE` to let the count number grows. Maybe Valine comment doesn't have these problems by right ACL choices, but counter system should have I think.

**Comment by stevenjoezhang** [comment]
Docs updated in https://github.com/theme-next/hexo-theme-next/commit/8c1b655d01773618331e84a34d547acdaf10bbbf
See also https://github.com/theme-next/hexo-theme-next/pull/926/files

**Comment by jijialinjuruo** [comment]
The code doesn't exist at all!

**Pull request merged**
