### PR TITLE
Fix image line number calculation error, the picture can not be fully loaded

### PR DESCRIPTION
**Pull request by guopengd**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

picture not loading properly

Issue resolved: N/A

## What is the new behavior?

picture loaded correctly

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
none

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by 1v9** [comment]
Any demo?

**Comment by guopengd** [comment]
My English is poor.Wait a moment,I make a demo.




------------------ 原始邮件 ------------------
发件人: "1v9"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午4:17
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com>;
抄送: "郭鹏东"<648276765@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [theme-next/hexo-theme-next] Fix image line number calculationerror, the picture can not be fully loaded (#929)




Any demo?

**Comment by guopengd** [comment]
http://blog.gpdstudy.club/photos/



I want five lines,but four lines


------------------ 原始邮件 ------------------
发件人: "1v9"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午4:17
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com>;
抄送: "郭鹏东"<648276765@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [theme-next/hexo-theme-next] Fix image line number calculationerror, the picture can not be fully loaded (#929)




Any demo?

**Comment by guopengd** [comment]
This is my code.
```
{% gp Defaults Layout %}
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
{% endgp %}
```

**Comment by stevenjoezhang** [comment]
Wait... Group picture feature is gonna to be fully refactored. https://github.com/theme-next/hexo-theme-next/issues/713

**Comment by 1v9** [comment]
I have a question, why your GP normal...

**Comment by guopengd** [comment]
ha? because my code hava "layout:post",this my code:
```
title: 图库
date: 2019-06-02 12:49:19
layout: post
type: photos

```




------------------ 原始邮件 ------------------
发件人: "ᴍɪᴍɪ"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 晚上6:14
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com>;
抄送: "郭鹏东"<648276765@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [theme-next/hexo-theme-next] Fix image line number calculationerror, the picture can not be fully loaded (#929)




Wait... Group picture feature is gonna to be fully refactored. #713

**Comment by 1v9** [comment]
@guopengd It seems that you have some personal modifications.

**Comment by guopengd** [comment]
Maybe, I usr "fancybox" plug.（我用了插件fancybox）




------------------ 原始邮件 ------------------
发件人: "1v9"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 晚上6:41
收件人: "theme-next/hexo-theme-next"<hexo-theme-next@noreply.github.com>;
抄送: "郭鹏东"<648276765@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [theme-next/hexo-theme-next] Fix image line number calculationerror, the picture can not be fully loaded (#929)




@guopengd It seems that you have some personal modifications.

**Comment by guopengd** [comment]
@1v9 
哦，对了，因为group-pictures.style里面我看到两行代码，他禁止了浮动，我就把它删了。fancybox插件是为了增加图片查看的效果，我英语不好，不懂你问的什么意思。如果你是问排版为什么对，那是因为我删除了两行代码。如果是为什么我能放大图片，则是因为fancybox插件。这么长，我翻译不来

```
.page-post-detail .post-body .group-picture-column {
  // float: nowne;
  margin-top: 10px;
  // width: auto !important;
  img { margin: 0 auto; }
}
```

**Comment by guopengd** [comment]
@1v9 
”photos“ setting:
---
layout: post
---

“group-pictures.styl' setting:
```
.page-post-detail .post-body .group-picture-column {
 ~~float: none;~~
  margin-top: 10px;
 ~~width: auto !important;~~
  img { margin: 0 auto; }
}
```
well,That can work normal.

**Comment by 1v9** [comment]
@guopengd 对的 我是问排版，这个之前有过讨论了，不过我们团队好像都忘了 😂

**Comment by guopengd** [comment]
@1v9 哈哈，能中文交流就好，我英语太差了，四级都没过。其实就是你们在GP的css上设置了禁止float，我当时看也不知道用意在哪，就删了

**Comment by 1v9** [comment]
@guopengd 我照你这个整了下，12 x 1 的布局

**Comment by guopengd** [comment]
@1v9 
https://github.com/guopengd/guopengd.github.io/blob/hexo/themes/next/source/css/_common/components/tags/group-pictures.styl
https://github.com/guopengd/guopengd.github.io/blob/hexo/source/photos/index.md
这两个都要设置，在图片的布局设置成post的布局，然后把css禁止浮动删掉就可以了，因为我发现这个js只有在post布局下会引入

**Comment by guopengd** [comment]
@1v9 不能发地址，我把设置的代码发一下吧
```
---
title: 图库
date: 2019-06-02 12:49:19
layout: post
type: photos
---
{% gp Defaults Layout %}
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
![](https://images2.alphacoders.com/747/thumb-1920-747093.jpg)
{% endgp %}
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1368521705&auto=1&height=66"></iframe>
```
然后在“source/css/_common/components/tags/group-pictures.styl”的代码改为：
```
.post .post-body .group-picture {
  img {
    box-sizing: border-box;
    padding: 0 3px;
    border: none;
  }
}

.post .group-picture-row {
  overflow: hidden;
  margin-top: 6px;
  &:first-child { margin-top: 0; }
}

.post .group-picture-column { float: left; }

.page-post-detail .post-body .group-picture-column {
  // float: nowne;
  margin-top: 10px;
  // width: auto !important;
  img { margin: 0 auto; }
}

.page-archive {
  .group-picture-container { overflow: hidden; }
  .group-picture-row {
    float: left;
    &:first-child { margin-top: 6px; }
  }

  .group-picture-column {
    max-width: 150px;
    max-height: 150px;
  }
}
```
这样设置之后，布局就能正常显示了

**Pull request merged**
