### PR TITLE
Fixed `reward` button vertical align text

### PR DESCRIPTION
**Pull request by 1v9**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

[](https://i.loli.net/2019/03/16/5c8c700f4182e.gif)

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Will be fixed in https://github.com/theme-next/hexo-theme-next/pull/689.
屏幕快照 2019-03-16 上午11 43 55
No need to add a hardcoded line height, I think

**Comment by 1v9** [comment]
@stevenjoezhang 😂 I found this because I tried to add option for animation of reward.

**Comment by 1v9** [comment]
is ok to remove W&H?

**Comment by stevenjoezhang** [comment]
You can merge it, and I'll update #689 then
Also see this: https://github.com/iissnan/hexo-theme-next/issues/1856

**Comment by 1v9** [comment]
@stevenjoezhang yes I saw that in roadmap, this is new style

**Comment by 1v9** [comment]
New style is nice I think, how we solve this?

**Comment by ivan-nginx** [comment]
> Will be fixed in #689.
> 屏幕快照 2019-03-16 上午11 43 55
> No need to add a hardcoded line height, I think

> You can merge it, and I'll update #689 then
> Also see this: [iissnan/hexo-theme-next#1856](https://github.com/iissnan/hexo-theme-next/issues/1856)

See what I'm talking about mixed before? About mixed Features & Fixes & Optimizations. This approach more troubles than we think. :last_quarter_moon:

**Comment by ivan-nginx** [comment]
> @stevenjoezhang yes I saw that in roadmap, this is new style
> 

Maybe a little bigger? + 3-5px. It's a little bit hard to click on donate...

**Comment by stevenjoezhang** [comment]
@ivan-nginx Emm.. I hardly agree it's "mixed".  When I implement a new feature, I found something is broken by it (reward button looks strange when font-size is larger than 20px), so I fixed it. Just like this animation shows:

animation 2019-03-16 12_09_53


Adding a new feature is not just adding a feature  🌗 Have to handle the bugs caused by this feature

**Comment by 1v9** [comment]
@ivan-nginx @stevenjoezhang For me, both styles are acceptable, but it's indeed a bit crowded if #689 merged. Maybe keep it like before?

**Comment by stevenjoezhang** [comment]
@1v9  Maybe you can fix this: https://github.com/iissnan/hexo-theme-next/pull/687#issuecomment-327529147
Add an option?

**Comment by 1v9** [comment]
@stevenjoezhang you mean roll animation? It's done but I'm finding is there a better code, you know I'm not an expert.

**Comment by stevenjoezhang** [comment]
@1v9 Don't worry, take your time. There is a lot of feature requests about reward button, like this: https://github.com/iissnan/hexo-theme-next/pull/687#issuecomment-256001010 😂

**Comment by ivan-nginx** [comment]
> Add an option?

Yes, add an option and by default don't shake label under the cursor.

**Comment by stevenjoezhang** [comment]
And this issue: https://github.com/theme-next/hexo-theme-next/issues/596. Maybe we need to refactor this function.

**Comment by ivan-nginx** [comment]
Dynamic unlimited additions?

**Comment by stevenjoezhang** [comment]
@ivan-nginx Yes. And this one: https://github.com/iissnan/hexo-theme-next/pull/2199/files

**Comment by ivan-nginx** [comment]
@stevenjoezhang I mean: they repeat same code with just different names. I want to create something like enumeration of arrays to provide any unlimited pictures and names with donations. For example, see menu  & submenu(s) implementation with icons to them.

**Comment by stevenjoezhang** [comment]
@ivan-nginx Yes, I understand what you mean.

**Pull request merged**
