### PR TITLE
Add support for automatic equation numbering for Mathjax, update the related documentation

### PR DESCRIPTION
**Pull request by jdhao**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse and Mist have been tested.
   - [x] Pisces and Gemini have been tested.
- [x] Docs have been added for features.

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [x] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): #264 . Currently, we can not number an equation and refer to it in our post.

## What is the new behavior?
Description about this pull, in several words...

* Screens with this changes
image

* Link to demo site with this changes
 https://jdhao.github.io/2018/01/25/hexo-mathjax-equation-number/

### How to use?
Do not need to change `_config.yml`. Just follow the guide in the MATH.md documentation.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@jdhao i don't know so much Math, so, need to wait review from members who now in better.

**Comment by jdhao** [comment]
Ok, I will wait for the reviews from the other developers :)

**Comment by sli1989** [comment]
- ALL tested in MATHJAX, there is no problem. 
- The zh-CN doc need to be modified accordingly.
- [The original linking of Automatic Equation Numbering in mathjax](http://docs.mathjax.org/en/latest/tex.html#automatic-equation-numbering) maybe need to be added.

**Comment by jdhao** [comment]
@sli1989 , I have added and official MathJax documentation and updated the corresponding Chinese documentation.

**Comment by chinsengi** [comment]
This feature breaks now, see [the demo](https://jdhao.github.io/2018/01/25/hexo-mathjax-equation-number/#mjx-eqn-eq5), links using \eqref become ???

**Pull request merged**
