### PR TITLE
hide single post or posts in specific categories on the home page

### PR DESCRIPTION
**Pull request by Seven-Steven**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Hide single post or posts in specific categories on the home page.

Issue Number(s): #385

## What is the new behavior?
Hide single post or posts in specific categories on the home page.

* Screens with this changes: 

  emmmmmmm......
  I think screens can't show this feature well, what I did is just hide some posts on the home page.

* Link to demo site with this changes: [Seven's blog](diqigan.cn)

### How to use?
In NexT `_config.yml`:
```yml
# Hide single post or posts in specific categories on the home page
#  If `hide_post` is `true`, you need to add `hide: true` in your post which you want to hide on the home page.
#  If you enabled the item `hide_categories`, you need just list the categories which you want to hide on the home page under the item `categories`.
hide:
  hide_post: false
  hide_categories:
    enable: false
    categories:
#     - categorie1
#     - categorie2
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by Seven-Steven** [comment]
Here is a document of how to use this feature.  [Document](http://diqigan.cn/20180811/hexo-hide-post-on-the-home-page.html#more)

**Comment by Seven-Steven** [comment]
@ivan-nginx 
emmmm..... So embarrassed, I just don't know where to add the docs in.
Should I write the docs in `_config.yml` or somewhere else?

**Comment by Seven-Steven** [comment]
@ivan-nginx 
I think it's better to add some comments in the `_config.yml` .

like this:

```json
# Hide single post or posts in specific categories on the home page
#  If `hide_post` is `true`, you need to add `hide: true` in your post which you want to hide on the home page.
#  If you enabled the item `hide_categories`, you need just list the categories which you want to hide on the home page under the item `categories`.
hide:
  hide_post: false
  hide_categories:
    enable: false
    categories:
#     - categorie1
#     - categorie2
```

And my English is not very good actually, so is there anythig wrong in my comments?

**Comment by ivan-nginx** [comment]
> I think it's better to add some comments in the _config.yml .
Yeah, pretty nice!

**Comment by Seven-Steven** [comment]
@ivan-nginx 
Thanks a lot for your affirmation.

**Comment by ivan-nginx** [comment]
Need to check it for speed. With many posts. It's index file and i think will slowing down during generate site with ~500 posts or more. Please, need to test it.

**Comment by Seven-Steven** [comment]
I'll try to make it better, thanks for your advice.

**Comment by stevenjoezhang** [comment]
Any progress you've already made? I'm happy to help with this issue.

**Comment by stevenjoezhang** [comment]
@Seven-Steven Another problem, the changes in `layout/index.swig` will not only affect the home page.

**Comment by Seven-Steven** [comment]
> @Seven-Steven Another problem, the changes in `layout/index.swig` will not only affect the home page.

emmmm... that's all what I want todo. Do you have other ideas?

**Comment by Seven-Steven** [comment]
> Need to check it for speed. With many posts. It's index file and i think will slowing down during generate site with ~500 posts or more. Please, need to test it.

Sorry for the delay.

I hava already made a test today under the environment below:
```
OS: Ubuntu 18.10
CPU: Intel® Core™ i5-4200U CPU @ 1.60GHz × 4 
RAM: 7.7 GiB
Hexo: 3.8.0
node: 8.11.4
```

I made 790 posts to run the test:
image
And the file size is 5.1Mb in total:
image

Before set the "hide" param, it took 2.9min to generate all the posts:
image

Then I enabled the setting "hide_post", and add a line "hide: true" for all the posts.
 It took 1.9min to generate all the posts:
image

At last, I enabled the setting "hide_categories", and add a line "categories: hide" for all the posts.
It took 1.83 min to generate all the posts:
image

That's all, It seems that it can save a little time to generate posts by hide posts on the home page.

**Comment by Seven-Steven** [comment]
And I find a bug here, if you hide some posts on the home page by this PR, the pagination will still count the hiden posts in.
image
I's not serious for me(uaually, I need just hide a few posts), but I'm not sure if it will trouble others.

**Comment by Seven-Steven** [comment]
@stevenjoezhang 
Brilliant! Thank's for your advice! I'll do it later.

**Comment by Seven-Steven** [comment]
> And I find a bug here, if you hide some posts on the home page by this PR, the pagination will still count the hiden posts in.
> image
> I's not serious for me(uaually, I need just hide a few posts), but I'm not sure if it will trouble others.

After @stevenjoezhang 's advicing, this is not a problem any more, I think.

**Comment by Seven-Steven** [comment]
@ivan-nginx 
About this feature, I got an idea, searched for information, tried to realize the function and made this PR to share my achievement. I didn't know there's a plugin which can achieve the same function until now.
I viewed the plugin [hexo-generator-index2](https://github.com/Jamling/hexo-generator-index2) just now, and I think this plugin may be better than my way.
If necessary, I can make a compare between the plugin and this PR later.
Thanks very much for your reply.

**Comment by ivan-nginx** [comment]
@Seven-Steven same plugin can be created just under the NexT in this path:
https://github.com/theme-next/hexo-theme-next/tree/master/scripts

**Comment by Seven-Steven** [comment]
@ivan-nginx 
I am doing the compare between the plugin "hexo-generator-index2" and this PR now. the version of Next is just the same as this repository.
There's 700 posts in my "_posts" directory: 
* using the default setting, it took 2.88 min to generate all the posts:
  ```shell
INFO  1245 files generated in 2.88 min
```
* using the plugin hexo-generator-index2, it took 2.92 min to generate all the posts:
```shell
INFO  1245 files generated in 2.92 min
```
(I ran the generate command again, and it took 2.82min.)
* then I changed the Next version to this PR, and hide the same categories as the plugin hexo-generator-index2, it took 2.92min:
```shell
INFO  1245 files generated in 2.92 min
```

Only considering the speed, it seems that the plugin and the PR is just the same. About the paginate the plugin does perform better.

To be honest, I am neither familiar with the Complete architecture of next nor javascript language. To fix the paginate by script, I need some time to learn all these things. It could take a time, really sorry about this.

That's all. Thanks.

**Comment by stevenjoezhang** [comment]
How about `hide:` option in post front matter?

**Comment by ivan-nginx** [comment]
Why it's needed, can u explain?

**Comment by stevenjoezhang** [comment]
Emm.. maybe a hexo plugin would be better. Speeding up the generating process is more important

**Comment by ivan-nginx** [comment]
> maybe a hexo plugin would be better

Yes.

**Comment by stevenjoezhang** [comment]
@Seven-Steven I'll fork `hexo-generator-index`, then implement this feature, and maybe also the `post-sticky` feature (https://github.com/theme-next/hexo-theme-next/issues/447)

**Comment by Seven-Steven** [comment]
@stevenjoezhang Thanks a lot.

**Pull request closed without merging**
