### PR TITLE
Make font-size customized only when `theme.font.enable` is true

### PR DESCRIPTION
**Pull request by daya0576**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
@stevenjoezhang are u think this is good? Because font-size and font-family – independence options.

**Comment by stevenjoezhang** [comment]
@ivan-nginx In my opinion, `enable` option of `tagcloud` and `font` is redundant. If no font families are set, the font setting has the same effect as `enable: false`

**Comment by Mryan2005** [comment]
@stevenjoezhang

**Comment by Mryan2005** [comment]
@ivan-nginx why

**Comment by stevenjoezhang** [comment]
The current situation and documentation are consistent:
https://github.com/theme-next/hexo-theme-next/blob/2637c53ab3ea8104a3ab5b2b8921b55eba2f42a8/_config.yml#L478-L481

Maybe it would be better to keep it as is?

**Pull request merged**
