### PR TITLE
Avoid recalculating the number of tags and categories

### PR DESCRIPTION
**Pull request by jiangtj**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
Become slower when it tags/categories are more.
Issue resolved: https://github.com/theme-next/hexo-theme-next/issues/661  https://github.com/theme-next/hexo-theme-next/issues/539

## What is the new behavior?
faster

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by jiangtj** [comment]
image
image

1.13min -> 31s

**Comment by jiangtj** [comment]
Revert啦，忽略呀

**Comment by ivan-nginx** [comment]
Revert Reason?

**Comment by stevenjoezhang** [comment]
A better solution: https://github.com/theme-next/hexo-theme-next/pull/976
Wait for Hexo to fix the bug in their code

**Pull request merged**
