### PR TITLE
Allow setting sidebar position to left or right in scheme Muse & Mist

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: #164

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [x] Yes.
- [ ] No.

https://github.com/theme-next/hexo-theme-next/pull/156/files#diff-90c3d2a8522cb0e6c0ac99af79e65607R9

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Need to test if the bug in #164 still exists

**Comment by stevenjoezhang** [comment]
Fixed bug 3, can't reproduce bug 1 & 2

**Comment by stevenjoezhang** [comment]
I suggest merging this PR first. For the issues it may cause, solve them in #951

**Comment by jiangtj** [comment]
image

O.O

**Comment by stevenjoezhang** [comment]
@jiangtj already fixed in https://github.com/theme-next/hexo-theme-next/pull/951

**Pull request merged**
