### PR TITLE
Revert #42, #87

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
~~Wait for https://github.com/hexojs/hexo/pull/3624 and / or Hexo v4.0 release.~~

**Comment by stevenjoezhang** [comment]
Should we merge this PR or wait for https://github.com/hexojs/hexo/pull/3624 ?

**Comment by ivan-nginx** [comment]
I think we can wait a little. I have some idea about it.

**Comment by stevenjoezhang** [comment]
This bug only occurs when the user uses the `_draft` folder, we can advise the users to avoid this in the documentation.

**Comment by stevenjoezhang** [comment]
This bug only appears when the user uses the `_draft` folder. We can recommend not using `_draft` in the documentation.

**Comment by ivan-nginx** [comment]
> This bug only appears when the user uses the `_draft` folder. We can recommend not using `_draft` in the documentation.

Yep, good idea.

**Pull request merged**
