### PR TITLE
Added `ready for review` in PR template

### PR DESCRIPTION
**Pull request by 1v9**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?
`WIP Expected — Waiting for status to be reported`

## What is the new behavior?

Adapt to [🚧 WIP installion](https://github.com/apps/wip/installations/793296).
PR author can decide wheather his PR is ready for review and pass WIP check.

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by 1v9** [comment]
😂 It's a little strange that we have WIP check and project cards at the same time.

**Comment by stevenjoezhang** [comment]
Do we really need WIP ?

**Comment by 1v9** [comment]
> Do we really need WIP ?

It's not bad except that pending status.

**Comment by stevenjoezhang** [comment]
Thanks to GitHub: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Pull request closed without merging**
