### PR TITLE
Fixed Disqus URL. Again. A little bit hard.

### PR DESCRIPTION
**Pull request by ivan-nginx**
issues: #494, #504.

### CODE REVIEW

**Comment by maple3142** [comment]
Is there any reason not to serialize it a json string?

**Comment by stevenjoezhang** [comment]
Maybe should replece all `'{{ page.permalink }}'` and `'{{ page.path }}'` with `{{ page.permalink|json }}` and `{{ page.path|json }}`, not only in disqus?

**Comment by ivan-nginx** [comment]
Maybe...

**Comment by ivan-nginx** [comment]
@Raincal @maple3142 make your decision...

**Comment by ivan-nginx** [comment]
@stevenjoezhang need to test other comments systems. Mb in others this bug doesn't appear.

**Comment by Raincal** [comment]
I find a bug, if the filename of MarkDown contains `"`, the post link doesn't contain it.

2018-12-13 05 33 44 am

2018-12-13 05 35 43 am

2018-12-13 05 38 25 am

**Comment by maple3142** [comment]
Imagine `page.path` is `"test'`.
Original method:
`'{{ page.path }}'` will turn into `'"test''` (syntax error)
My method(json serialization) will turn it into `"\"test'"`, and javascript parser will intepret it as `"test'`.
@Raincal method will convert it into `%22test'`, but it will encode non-english character too, which differ from the original method.

**Comment by Raincal** [comment]
@maple3142 	
我到 Disqus 管理面板看了下, 如果没有encoding 的话 Disqus 会自动帮我们 encoding, 两种方式`"`都会变成 %22
现在唯一不同的是非英文字符, 比如`Disqus测试`
```
Disqus%e6%b5%8b%e8%af%95	// 自动编码
Disqus%E6%B5%8B%E8%AF%95	// 手动编码
```
转换后大小写不一样，Disqus 会认为是两个不同的帖子

总结:
- 从其他平台或主题且 this.page.url 或 identifier 是从 window.location.xx 获取的
- 用了诸如 https://github.com/fooleap/disqus-php-api 这种代理服务的

上述两种情况在此处 encoding 比较好

**Comment by maple3142** [comment]
identifier 直接用中文和 encoding 過的會有不同嗎？
因為舊的方法 identifier 會直接出現中文，而如果 encoding 過可能會導致失去評論的問題

**Comment by ivan-nginx** [comment]
Guys, let's take less damaged variant. Both variants are good in its own way and as for me – no need thinking a long time what choise is better. And else thing: in browser adress bar should never be any quotes (single or double or code quote) – there are service characters which often need for coding (e.g. JS). So, if dude write in post this characters, it's his own problem, not problem of coders. BTW, i also write permalints only in EN with dots (e.g. `/docs/third-party-services/content-sharing-services/`) – always and anywhere working fine. :smile_cat: 

So, poll for method? http://www.easypolls.net/poll.html?p=5c11e2a3e4b0dbbd44ad63bb

**Comment by Raincal** [comment]
@maple3142 
昨天我只看了这里
2018-12-13 08 28 34 pm
刚才请求了下 API ,能看到 identifier 了
identifier 确实不一样，未编码时存的是Unicode，所以还是用你那种方法吧，对 next 老用户比较友好
对于我上面讲的那两种情况，在配置 url 和 identifier 时先 decode 下或用迁移工具重新匹配下就不会丢失评论了
```json
{
  "response":[
    {
      "link":"https://next-test.com/2018/12/12/Disqus%E6%B5%8B%E8%AF%95%22/",
      "slug":"disqus_72",
      "forum":"next-dev",
      "identifiers":[
        "2018/12/12/Disqus%E6%B5%8B%E8%AF%95%22/"
      ]
    },
    {
      "link":"https://next-test.com/2018/12/12/Disqus%e6%b5%8b%e8%af%95%22/",
      "slug":"disqus",
      "forum":"next-dev",
      "identifiers":[
        "2018/12/12/Disqus\u6d4b\u8bd5\"/"
      ]
	}
  ]
}
```

**Comment by ivan-nginx** [comment]
So, what variant we choise?

**Pull request merged**
