### PR TITLE
Removed all hardcoded font sizes with replacing them on `em`.

### PR DESCRIPTION
**Pull request by ivan-nginx**
Refactoring of #689 pull.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
`px` is not only used in `font-size`, need to do more tests if change the unit to `em` (especially on mobile).

**Comment by ivan-nginx** [comment]
I right now worked with this PR. Wait for pushes...

**Comment by ivan-nginx** [comment]
What are u doing?

**Comment by stevenjoezhang** [comment]
I found two styl files have almost the same content, so I deleted one of them in https://github.com/theme-next/hexo-theme-next/pull/724 ... this caused a merge conflict so I resolved it ... run `git pull` should work fine

**Comment by ivan-nginx** [comment]
Please, don't touch this pull. I'm working with him and u make pushes to my pull & branch.

**Comment by stevenjoezhang** [comment]
Superseded by #1005, #1006

**Pull request closed without merging**
