### PR TITLE
Add Google Analytics Pageview

### PR DESCRIPTION
**Pull request by maple3142**
## PR Checklist 

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [ ] Bugfix.
- [x] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

Add an much lighter alternative to normal Google Analytics, as it requires no external script.

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
# Google Analytics Pageview
google_analytics_pageview:
  tracking_id: # <app_id>
```
Find `google_analytics_pageview.tracking_id` and fill it.

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
Can you confirm that the script is PJAX compatible? Because `load` event may only trigger once on the page, thus the callback function may not be executed after PJAX refresh.

**Comment by maple3142** [comment]
@stevenjoezhang Is there a PJAX callback for doing that?

**Comment by stevenjoezhang** [comment]
Is it possible to change the function from the callback of the `load` event to IIFE?

**Comment by maple3142** [comment]
@stevenjoezhang Yes, but I wonder whether there's a way to detect if page changed(loaded by PJAX).

**Comment by stevenjoezhang** [comment]
`pjax:success` event

**Comment by maple3142** [comment]
This should now work with PJAX now.

**Comment by 1v9** [comment]
Test passed when pjax enabled, I checked it in analytics realtime panel.

**Comment by 1v9** [comment]
https://developers.google.com/analytics/devguides/collection/gtagjs/migration
https://developers.google.com/analytics/devguides/collection/gtagjs/pages

**Comment by maple3142** [comment]
@1v9 In fact, the purpose of this PR is to have a basic analytics data without having to include bloated(IMO) `analytics.js` and `gtag.js`. Therefore, I am not interested to add them, since the normal version of GA already did much more than this script.

**Comment by 1v9** [comment]
@maple3142 OK I know, you mean a slimmer version to do less work

**Comment by 1v9** [comment]
Would you add docs for this feature?

**Comment by 1v9** [comment]
Wait, I have some work to do, I won't change the existing implementation, and I will push updates and documentation as soon as I'm done.

**Comment by maple3142** [comment]
Added https://github.com/theme-next/theme-next.org/commit/df36c7c7dcb6369948b108216f6ad7c6a509104f

**Pull request merged**
