### PR TITLE
Fix valine & disqus meta for #1305

### PR DESCRIPTION
**Pull request by sli1989**
## PR Checklist 

- [ ] The commit message follows [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml

```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [ ] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
`disqus` also need to be modified

https://github.com/theme-next/hexo-theme-next/blob/c4796bdeb50d38d4c1ee581156b9ea66223be938/scripts/filters/comment/disqus.js#L34

**Comment by jiangtj** [comment]
@sli1989 I saw the doc https://valine.js.org/visitor.html , but its configuration is not the same as in next. Can you try using the configuration in the documentation?

**Comment by sli1989** [comment]
I am fused about detailed programming stuffs.
For now, it works fine and intergrated in Next.
#345 was pulled by @xCss. u may ask him for this.

**Comment by stevenjoezhang** [comment]
Looks like there is no problem with valine, I think this PR can be merged

**Pull request merged**
