### PR TITLE
Update README.md, remove unused URLs

### PR DESCRIPTION
**Pull request by stevenjoezhang**
Changes:
* In Vi's repo there are many URLs in `README.md`, but most of them are removed now... However the link of them are keeped. This PR moves them into the `<!-- -->` comment

* Deleted a link to an expired website
See: https://github.com/iissnan/hexo-theme-next/commit/020109d29c5024a5220d761add0858f25734c624#diff-4b29e98dc086ca7ee0e534c9eb921739

## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [ ] Tests for the changes was maked (for bug fixes / features).
   - [ ] Muse | Mist have been tested.
   - [ ] Pisces | Gemini have been tested.
- [ ] Docs in [NexT website](https://theme-next.org/docs/) have been added / updated (for new features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [x] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
@ivan-nginx `https://blog.zzbd.org` is not accessible now.
`feature-request` was renamed to `%22Feature+Request%22`

**Comment by 1v9** [comment]
@stevenjoezhang His certificate has expired but site is available.

**Comment by ivan-nginx** [comment]
> @ivan-nginx `https://blog.zzbd.org` is not accessible now.
> `feature-request` was renamed to `%22Feature+Request%22`

Yep, only this 2 changes enough.

**Comment by stevenjoezhang** [comment]
@1v9 Seems it was redirected to this: https://dnspod.qcloud.com/static/block.html?d=blog.zzbd.org

**Comment by stevenjoezhang** [comment]
@ivan-nginx OK, I'll revert some changes

**Comment by ivan-nginx** [comment]
@stevenjoezhang also, u can do like me: create local branch and then push this your local branch to remote repo, to this repo (coz u have Admin rights, all members they have). It will be able to change branch here and see live preview **before pull merged**.

Example: https://github.com/theme-next/hexo-theme-next/blob/security-section/docs/zh-CN/CONTRIBUTING.md

**Comment by stevenjoezhang** [comment]
@ivan-nginx Thanks, this is a better solution 👍

**Pull request merged**
