### PR TITLE
Rebuild ALL-CONTRIBUTORS-LIST in README.md

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes was maked (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [ ] [Docs](https://github.com/theme-next/theme-next.org/tree/source/source/docs) in [NexT website](https://theme-next.org/docs/) have been added / updated (for features).

## PR Type
**What kind of change does this PR introduce?**

- [ ] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [x] Other... Please describe:

## What is the current behavior?

Issue resolved: N/A

## What is the new behavior?

- Screenshots with this changes: N/A
- Link to demo site with this changes: N/A

### How to use?
In NexT `_config.yml`:
```yml
...
```

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by 1v9** [comment]
What's this PR for? Seems we have a plan to migrate CONTRIBUTORS to another position.

**Comment by stevenjoezhang** [comment]
@1v9 to apply https://github.com/theme-next/hexo-theme-next/pull/756
https://github.com/theme-next/hexo-theme-next/pull/756#issuecomment-478026929

**Comment by 1v9** [comment]
https://github.com/theme-next/hexo-theme-next/blob/readme/README.md#contributors

**Comment by stevenjoezhang** [comment]
We can give everyone more badges and make the forms look better 😂

> 白宫的一个灯泡烧坏了，尼克松按了一下按钮，一个工作人员走进来换了个灯泡。尼克松给了他五美元。
克里姆林宫的一个灯泡坏了，勃列日涅夫的侍卫叫来一名工作人员换了一个灯泡。勃列日涅夫给了他一枚列宁奖章，也给了那名工作人员一枚列宁奖章。勃列日涅夫觉得不错，又给了自己一枚列宁奖章。

**Comment by ivan-nginx** [comment]
So, there is the list now?

**Comment by stevenjoezhang** [comment]
@ivan-nginx Moved to here: https://github.com/theme-next/hexo-theme-next/blob/master/docs/AUTHORS.md

**Pull request merged**
