### PR TITLE
Fix single quotes in lean-analytics.swig are not escaped

### PR DESCRIPTION
**Pull request by LEAFERx**
## PR Checklist
**Please check if your PR fulfills the following requirements:**

- [x] The commit message follows [our guidelines](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md).
- [x] Tests for the changes have been added (for bug fixes / features).
   - [x] Muse | Mist have been tested.
   - [x] Pisces | Gemini have been tested.
- [x] Docs have been added / updated (for bug fixes / features).

## PR Type
**What kind of change does this PR introduce?**  

- [x] Bugfix.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [ ] Documentation content changes.
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number(s): #169 

## Does this PR introduce a breaking change?
- [ ] Yes.
- [x] No.

### CODE REVIEW

**Comment by sli1989** [comment]
It's better to added in theme's `_config.yml`.

**Comment by LEAFERx** [comment]
@sli1989 ?

**Comment by sli1989** [comment]
like this [commit](https://github.com/theme-next/hexo-theme-next/pull/170/commits/56074e1e70ddecaff3e1001967fa30eb03bf33a3). I pulled the wrong branch, so close it.

**Comment by ivan-nginx** [comment]
@sli1989 affermative it. Need to add this descrition in NexT config, and i'm talking about it before, as i remember.

**Comment by LEAFERx** [comment]
annotation added

**Comment by sli1989** [comment]
Ask a digression, how to add commit in other's PR as a administrator? It seem no branch for a PR.

**Comment by ivan-nginx** [comment]
> how to add commit in other's PR as a administrator

1. Just edit files in «Files changed» tab (https://github.com/theme-next/hexo-theme-next/pull/171/files). But in this case u can't to edit new files, only files which shown in «Files changed» tab.
2. Add pull as remote, checkout it and chenge what u want. Then `push` — will be pushed your commits in current pull directly. In this case u can edit any files from repo.

**Comment by sli1989** [comment]
@ivan-nginx thanks.

**Pull request merged**
